### ISSUE TITLE
Add getName to structures with a nameAlg field

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-pytss#104]
It would be useful to get the name NV areas and key objects without a ESAPI context when doing some types of attestation and audit sessions

**Comment by williamcroberts** [comment]
Which, in case you don't know the format, is:

uint16 hash alg + hash(nameAlg, marshalled public)

You can see it in the ESYS code nicely:

KEY: https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/esys_iutil.c#L1507
NV - https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/esys_iutil.c#L1453

**Comment by whooo** [comment]
Yeah, mostly a reminder for myself so I didn't forget about it
