### ISSUE TITLE
Creating objects from dicts

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-pytss#105]
Being able to create at least some type of objects (such as TPM2B_PUBLIC or TPM2B_NV_PUBLIC) from a dict could be an useful feature for users of the API.

By using dicts directly we can leave the (de)serialization part to the caller instead of enforcing a specific format such as JSON.

One use case that I have is that I want to create a NV counter on a remote system using ansible.
As ansible is a heavy user of YAML, so I want to define the NV area using an YAML hash, later on I want to do a audit session to attest the current counter value and therefor want to reuse the same YAML hash for generating the name locally to verify the audi session.

**Comment by williamcroberts** [comment]
I think because we use kwargs for the input parameters isn't this possible?

**Comment by whooo** [comment]
It doesn't seem to work for setting fields in child objects, I'll play with it a bit and see if I can get something reasonable working.
I'm more or less thinking of a subset of the FAPI JSON formats, excluding the FAPI specific parts, and nothing related to policies.

**Comment by williamcroberts** [comment]
> It doesn't seem to work for setting fields in child objects, I'll play with it a bit and see if I can get something reasonable working.
> I'm more or less thinking of a subset of the FAPI JSON formats, excluding the FAPI specific parts, and nothing related to policies.

Yeah right now it's limited to the object itself, child objects have to be instantiated from an instance of the child class, like:

TPM2B_PUBLIC(TPMT_PUBLIC({dict of stuff}))
