### ISSUE TITLE
Check input params

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#122]
Check params before we call the esapi library so we can give better errors than something like: TypeError: expected integer.

**Comment by whooo** [comment]
Some parameters should be able to be None as well (inPrivate for LoadExternal comes to mind).
It would also be nice if TPM2B_SIMPLE_OBJECT-based parameters could take bytes.

Unless you already started working on it I can throw something together

**Comment by williamcroberts** [comment]
> Some parameters should be able to be None as well (inPrivate for LoadExternal comes to mind).

Yep, I've been doing some of them as I go along. Im working TOP down in ESAPI I just finished EncryptDecrypt2. If you want to start add ESAPI tests starting from the BOTTOM we can meet in the middle. This way we don't have to deal with merge  conflicts constantly and dont dup work.

> It would also be nice if TPM2B_SIMPLE_OBJECT-based parameters could take bytes.

I think this is the case:
 - TPM2B_AUTH: https://github.com/tpm2-software/tpm2-pytss/blob/master/test/test_types.py#L1041
 - TPMS_ECC_POINT: x and y are TPM2B_ECC_PARAMETER (simple) and they get initialized by bytes.

I'd definitely welcome more tests to ensure it all behaves as expected in differing situations.

> 
> Unless you already started working on it I can throw something together

**Comment by whooo** [comment]
> > Some parameters should be able to be None as well (inPrivate for LoadExternal comes to mind).
> 
> Yep, I've been doing some of them as I go along. Im working TOP down in ESAPI I just finished EncryptDecrypt2. If you want to start add ESAPI tests starting from the BOTTOM we can meet in the middle. This way we don't have to deal with merge conflicts constantly and dont dup work.
> 
Sure, sounds good

> > It would also be nice if TPM2B_SIMPLE_OBJECT-based parameters could take bytes.
> 
> I think this is the case:
> 
>     * TPM2B_AUTH: https://github.com/tpm2-software/tpm2-pytss/blob/master/test/test_types.py#L1041
> 
>     * TPMS_ECC_POINT: x and y are TPM2B_ECC_PARAMETER (simple) and they get initialized by bytes.
> 
> 
I was thinking of bytes as arguments, so outsideInfo for Create as an example

**Comment by williamcroberts** [comment]
> > > Some parameters should be able to be None as well (inPrivate for LoadExternal comes to mind).
> > 
> > 
> > Yep, I've been doing some of them as I go along. Im working TOP down in ESAPI I just finished EncryptDecrypt2. If you want to start add ESAPI tests starting from the BOTTOM we can meet in the middle. This way we don't have to deal with merge conflicts constantly and dont dup work.
> 
> Sure, sounds good
> 
> > > It would also be nice if TPM2B_SIMPLE_OBJECT-based parameters could take bytes.
> > 
> > 
> > I think this is the case:
> > ```
> > * TPM2B_AUTH: https://github.com/tpm2-software/tpm2-pytss/blob/master/test/test_types.py#L1041
> > 
> > * TPMS_ECC_POINT: x and y are TPM2B_ECC_PARAMETER (simple) and they get initialized by bytes.
> > ```
> 
> I was thinking of bytes as arguments, so outsideInfo for Create as an example

Got it, yeah i've done that for some of them, like auth values.

**Comment by williamcroberts** [comment]
Finished in multiple commits
