### ISSUE TITLE
TypeError: in method 'Fapi_GetRandom', argument 3 of type 'uint8_t **'

### ISSUE THREAD

**Issue by lap1nou** [tpm2-software/tpm2-pytss#131]
Hi,

I just installed the library and wanted to test it with a simple example:
```python
from tpm2_pytss.fapi import FAPI, FAPIDefaultConfig
from tpm2_pytss.binding import *

fapi = FAPI()

fapi.get_random(10)
```
But I got this error:
```
Traceback (most recent call last):
  File "tpm.py", line 6, in <module>
    fapi.get_random(10)
  File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/fapi.py", line 196, in get_random
    self.GetRandom(length, datapp)
  File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/context.py", line 78, in wrapper
    return custom_wrap(func)(self.ctxp, *args, **kwds)
  File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/context.py", line 112, in wrapper
    result = func(self, *args, **kwds)
  File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/util/swig.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/exceptions.py", line 48, in wrapper
    rc = func(*args, **kwargs)
  File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/fapi_binding.py", line 10790, in Fapi_GetRandom
    return _fapi_binding.Fapi_GetRandom(context, numBytes, data)
TypeError: in method 'Fapi_GetRandom', argument 3 of type 'uint8_t **'
```
Any idea ?

**Comment by williamcroberts** [comment]
> Hi,
> 
> I just installed the library and wanted to test it with a simple example:
> 
> ```python
> from tpm2_pytss.fapi import FAPI, FAPIDefaultConfig
> from tpm2_pytss.binding import *
> 
> fapi = FAPI()
> 
> fapi.get_random(10)
> ```
> 
> But I got this error:
> 
> ```
> Traceback (most recent call last):
>   File "tpm.py", line 6, in <module>
>     fapi.get_random(10)
>   File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/fapi.py", line 196, in get_random
>     self.GetRandom(length, datapp)
>   File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/context.py", line 78, in wrapper
>     return custom_wrap(func)(self.ctxp, *args, **kwds)
>   File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/context.py", line 112, in wrapper
>     result = func(self, *args, **kwds)
>   File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/util/swig.py", line 173, in wrapper
>     return func(*args, **kwargs)
>   File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/exceptions.py", line 48, in wrapper
>     rc = func(*args, **kwargs)
>   File "/home/pa/.local/lib/python3.8/site-packages/tpm2_pytss/fapi_binding.py", line 10790, in Fapi_GetRandom
>     return _fapi_binding.Fapi_GetRandom(context, numBytes, data)
> TypeError: in method 'Fapi_GetRandom', argument 3 of type 'uint8_t **'
> ```
> 
> Any idea ?

The fact I see swig in your stack trace means your mixing an old, defunct development version with the code from current master. The code moved from swig (too many issues), to using CFFI and they are not compatable. Can you install from master via git clone or something?

```bash
git@github.com:tpm2-software/tpm2-pytss.git
python3 -m pip install --user .
```

**Comment by lap1nou** [comment]
Oh thank you, this worked but now I'm facing another problem with the following code:

```python
from tpm2_pytss import *

fapi = FAPI()
fapi.provision()
test = fapi.get_random(10)

print(test)
```

```
ERROR:fapi:src/tss2-fapi/ifapi_helpers.c:2454:ifapi_get_curl_buffer() curl_easy_perform() failed: Couldn't resolve host name 
ERROR:fapi:src/tss2-fapi/fapi_crypto.c:1937:ifapi_verify_ek_cert() ErrorCode (0x00060025) Get certificate. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:827:Fapi_Provision_Finish() ErrorCode (0x00060025) Verify EK certificate 
ERROR:esys:src/tss2-esys/esys_iutil.c:394:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (ff). 
ERROR:esys:src/tss2-esys/esys_iutil.c:1105:esys_GetResourceObject() Unknown ESYS handle. ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:138:Esys_FlushContext_Async() flushHandle unknown. ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x0007000b) 
ERROR:fapi:src/tss2-fapi/fapi_util.c:1079:ifapi_session_clean() Cleanup session failed. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x00060025) Provision 
Traceback (most recent call last):
  File "../tpm.py", line 6, in <module>
    fapi.provision()
  File "/usr/local/lib/python3.8/dist-packages/tpm2_pytss/FAPI.py", line 206, in provision
    raise TSS2_Exception(ret)
tpm2_pytss.TSS2_Exception.TSS2_Exception: fapi:No certificate
```

Hum, as I understand it, the certificate of my TPM isn't valid or something like that, the problem is that my TPM is a virtual TPM installed with VMWare, I just wanted to use the TPM API for interacting with that virtual TPM (tpm2-tools command are working fine for example).

Have you got an example of code for me (I already saw example from the unit test in the /tests directory, and copied the provision part of the fapi from it).

**Comment by williamcroberts** [comment]
> Oh thank you, this worked but now I'm facing another problem with the following code:
> 
> ```python
> from tpm2_pytss import *
> 
> fapi = FAPI()
> fapi.provision()
> test = fapi.get_random(10)
> 
> print(test)
> ```
> 
> ```
> ERROR:fapi:src/tss2-fapi/ifapi_helpers.c:2454:ifapi_get_curl_buffer() curl_easy_perform() failed: Couldn't resolve host name 
> ERROR:fapi:src/tss2-fapi/fapi_crypto.c:1937:ifapi_verify_ek_cert() ErrorCode (0x00060025) Get certificate. 
> ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:827:Fapi_Provision_Finish() ErrorCode (0x00060025) Verify EK certificate 
> ERROR:esys:src/tss2-esys/esys_iutil.c:394:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (ff). 
> ERROR:esys:src/tss2-esys/esys_iutil.c:1105:esys_GetResourceObject() Unknown ESYS handle. ErrorCode (0x0007000b) 
> ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:138:Esys_FlushContext_Async() flushHandle unknown. ErrorCode (0x0007000b) 
> ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x0007000b) 
> ERROR:fapi:src/tss2-fapi/fapi_util.c:1079:ifapi_session_clean() Cleanup session failed. 
> ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x00060025) Provision 
> Traceback (most recent call last):
>   File "../tpm.py", line 6, in <module>
>     fapi.provision()
>   File "/usr/local/lib/python3.8/dist-packages/tpm2_pytss/FAPI.py", line 206, in provision
>     raise TSS2_Exception(ret)
> tpm2_pytss.TSS2_Exception.TSS2_Exception: fapi:No certificate
> ```
> 
> Hum, as I understand it, the certificate of my TPM isn't valid or something like that, the problem is that my TPM is a virtual TPM installed with VMWare, I just wanted to use the TPM API for interacting with that virtual TPM (tpm2-tools command are working fine for example).
> 
> Have you got an example of code for me (I already saw example from the unit test in the /tests directory, and copied the provision part of the fapi from it).

You need to do something like:
  - https://github.com/tpm2-software/tpm2-pytss/blob/fef34855c1e4637daeff040cea81d0d5af72d417/test/test_fapi.py#L26-L31

You need to get `"ek_cert_less" : "yes"` in your fapi config. If you are using the fapi install thats system wide, ( i think thats without the temp dir on provision, but I could be wrong I don't use fapi much) you can just edit your default fapi config file. The file should be at something like /usr/local/etc/tpm2-tss/fapi-config.json (I did an strace of tss2_provision to find it), and you can just manually add the line. Here is my conf file
```
{
     "profile_name": "P_ECCP256SHA256",
     "profile_dir": "/usr/local/etc/tpm2-tss/fapi-profiles/",
     "user_dir": "~/.local/share/tpm2-tss/user/keystore",
     "system_dir": "/usr/local/var/lib/tpm2-tss/system/keystore",
     "tcti": "",
     "system_pcrs" : [],
     "log_dir" : "/usr/local/var/run/tpm2-tss/eventlog/",
     "ek_cert_less" : "yes"
}
```

**Comment by lap1nou** [comment]
Thank you this worked nicely ! Are these things documented somewhere ? (all directive of the config file).

I guess we can close the issue.

**Comment by williamcroberts** [comment]
> Thank you this worked nicely ! Are these things documented somewhere ? (all directive of the config file).

man (5) fapi-config

> 
> I guess we can close the issue.
