### ISSUE TITLE
allow wrap for import

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#145]
Support a method on TPM2B_SENSITIVE to convert it to a TPM2B_PRIVATE capable for a call to Import ala what the tpm2-tools does:
  - https://github.com/tpm2-software/tpm2-tools/blob/cedf49de2e919ec32c2f104c3ea7b728b87f6714/tools/tpm2_import.c#L118

**Comment by williamcroberts** [comment]
@whooo any interest in this one ;-p ?

**Comment by whooo** [comment]
Sure, I was already thinking about doing it. I'll look into it when I port my MakeCredential code
