### ISSUE TITLE
Expose fapi_info

### ISSUE THREAD

**Issue by IshFx** [tpm2-software/tpm2-pytss#159]
Hello,

About the TODO here : https://github.com/tpm2-software/tpm2-pytss/blob/07a92e9fa75548ea102ce90b3b6182093b3f7a73/tpm2_pytss/FAPI.py#L157

How about simply exposing the FapiInfo instance ?

- Renaming `info` method to `get_info` because its not a property and it calls a C++ function GetInfo under the hood.
- Adding a property `info` that returns an instance of FapiInfo using the `get_info()` string data.

```py
def get_info(self) -> str:  # TODO other type? json?
    """Get Fapi information, containing library info, TPM capabilities and more.

    Raises:
        TSS2_Exception: If Fapi returned an error code.

    Returns:
        str: JSON-encoded info string.
    """
    info = ffi.new("char **")
    ret = lib.Fapi_GetInfo(self.ctx, info)
    if ret == lib.TPM2_RC_SUCCESS:
        result = ffi.string(info[0]).decode(self.encoding)
        lib.Fapi_Free(info[0])
        return result
    raise TSS2_Exception(ret)

@property
def info(self):
    info_data = json.loads(self.get_info())
    return FapiInfo(info_data)
```

This way there is no need to have multiple properties (like `version`, `config`, etc).
They would be accessible through `info` property using dot notation.

I can submit a PR if requested.

Thanks in advance !

**Comment by williamcroberts** [comment]
what not in FAPI `__init__` call the lib.FAPI_GetInfo and cache the value and have the info be a property that returns the cached info. I'm assuming that getinfo doesn't return non-static values.

However, the spec does say, "Fapi_GetInfo() returns a UTF-8 string identifying the version of the FAPI, the TPM, configurations and other relevant
information in a human readable format. The concrete content of this string is implementation specific."

I'm okay with making this a property, but I am not sure if we should interpret the string as JSON, as it might not be.

**Comment by williamcroberts** [comment]
@joholl thoughts?

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT thoughts as well?

**Comment by IshFx** [comment]
> what not in FAPI __init__ call the lib.FAPI_GetInfo and cache the value and have the info be a property that returns the cached info. I'm assuming that getinfo doesn't return non-static values.

I don't know if it's a good idea to call the GetInfo at instantiation because this would directly send a "TPM2_GetCapability" command to the TPM. Interacting with the TPM at instantiation might not be wanted by the user.

> I'm okay with making this a property, but I am not sure if we should interpret the string as JSON, as it might not be.

My proposal is to rename the existing method `info` to `get_info` because that what it does => it calls Fapi_GetInfo() under the hood.
Then Add an `info` property to abstract the access to the TPM information using this great class https://github.com/tpm2-software/tpm2-pytss/blob/07a92e9fa75548ea102ce90b3b6182093b3f7a73/tpm2_pytss/fapi_info.py.
This property can then be cached.

**Comment by williamcroberts** [comment]
> > what not in FAPI **init** call the lib.FAPI_GetInfo and cache the value and have the info be a property that returns the cached info. I'm assuming that getinfo doesn't return non-static values.
> 
> I don't know if it's a good idea to call the GetInfo at instantiation because this would directly send a "TPM2_GetCapability" command to the TPM. Interacting with the TPM at instantiation might not be wanted by the user.

Fair enough, I looked through the C code and it doesn't interact with the TPM.

> 
> > I'm okay with making this a property, but I am not sure if we should interpret the string as JSON, as it might not be.
> 
> My proposal is to rename the existing method `info` to `get_info` because that's what it does => it calls Fapi_GetInfo() under the hood.

Thats fine....

> Then Add an `info` property to abstract the access to the TPM information using this great class https://github.com/tpm2-software/tpm2-pytss/blob/07a92e9fa75548ea102ce90b3b6182093b3f7a73/tpm2_pytss/fapi_info.py.
> This property can then be cached.

I'm more concerned about the initial approach of the code base assuming the string coming back is JSON and then building a class to wrap that. What happens when it's not JSON? This code blows up. Since the spec states it's just a string, we shouldn't assume any formatting. Currently their is only one FAPI library in existence, and this is bindings to that library, but in theory someone could drop in another instance.

**Comment by IshFx** [comment]
> 
> 
> > > what not in FAPI **init** call the lib.FAPI_GetInfo and cache the value and have the info be a property that returns the cached info. I'm assuming that getinfo doesn't return non-static values.
> > 
> > 
> > I don't know if it's a good idea to call the GetInfo at instantiation because this would directly send a "TPM2_GetCapability" command to the TPM. Interacting with the TPM at instantiation might not be wanted by the user.
> 
> Fair enough, I looked through the C code and it doesn't interact with the TPM.

Oh, I thought Fapi_GetInfo calls "TPM2_GetCapability" command.

Doesn't this piece of code interact with TPM ?

https://github.com/tpm2-software/tpm2-tss/blob/adfa451c1ec362ac5ce19a644baf48d7003cb3d8/src/tss2-fapi/api/Fapi_GetInfo.c#L235

And

https://github.com/tpm2-software/tpm2-tss/blob/adfa451c1ec362ac5ce19a644baf48d7003cb3d8/src/tss2-fapi/fapi_util.c#L4042

> > Then Add an `info` property to abstract the access to the TPM information using this great class https://github.com/tpm2-software/tpm2-pytss/blob/07a92e9fa75548ea102ce90b3b6182093b3f7a73/tpm2_pytss/fapi_info.py.
> > This property can then be cached.
> 
> I'm more concerned about the initial approach of the code base assuming the string coming back is JSON and then building a class to wrap that. What happens when it's not JSON? This code blows up. Since the spec states it's just a string, we shouldn't assume any formatting. Currently their is only one FAPI library in existence, and this is bindings to that library, but in theory someone could drop in another instance.

I agree with you! If the goal of this (pytss) lib is to be 100% compliant with the FAPI spec, then there is no need to provide abstraction of `info` data, because the spec doesn't specify such abstraction.

**Comment by williamcroberts** [comment]
> > > > what not in FAPI **init** call the lib.FAPI_GetInfo and cache the value and have the info be a property that returns the cached info. I'm assuming that getinfo doesn't return non-static values.
> > > 
> > > 
> > > I don't know if it's a good idea to call the GetInfo at instantiation because this would directly send a "TPM2_GetCapability" command to the TPM. Interacting with the TPM at instantiation might not be wanted by the user.
> > 
> > 
> > Fair enough, I looked through the C code and it doesn't interact with the TPM.
> 
> Oh, I thought Fapi_GetInfo calls "TPM2_GetCapability" command because it should get the capabilities from the TPM.
> 
> Doesn't this piece of code interact with TPM ?

I should have been more specific Fapi_Initialize doesn't interact with the TPM.

> 
> https://github.com/tpm2-software/tpm2-tss/blob/adfa451c1ec362ac5ce19a644baf48d7003cb3d8/src/tss2-fapi/api/Fapi_GetInfo.c#L235
> 
> And
> 
> https://github.com/tpm2-software/tpm2-tss/blob/adfa451c1ec362ac5ce19a644baf48d7003cb3d8/src/tss2-fapi/fapi_util.c#L4042
> 
> > > Then Add an `info` property to abstract the access to the TPM information using this great class https://github.com/tpm2-software/tpm2-pytss/blob/07a92e9fa75548ea102ce90b3b6182093b3f7a73/tpm2_pytss/fapi_info.py.
> > > This property can then be cached.
> > 
> > 
> > I'm more concerned about the initial approach of the code base assuming the string coming back is JSON and then building a class to wrap that. What happens when it's not JSON? This code blows up. Since the spec states it's just a string, we shouldn't assume any formatting. Currently their is only one FAPI library in existence, and this is bindings to that library, but in theory someone could drop in another instance.
> 
> I agree with you! If the goal of this (pytss) lib is to be 100% compliant with the FAPI spec, then there is no need to provide abstraction of `info` data, because the spec doesn't specify such abstraction.

Exactly, we may wish to dump this functionality before release. But if you want to, for now, just make info be get_info to match the rest of the API, thats fine.

@joholl and I also diverged in ESAPI vs FAPI function naming. I went camelcase and @joholl went underscore. I'd also like to converge before release so the code base looks more consistent.

**Comment by joholl** [comment]
> My proposal is to rename the existing method info to get_info because that's what it does => it calls Fapi_GetInfo() under the hood.

That is a very good point. The goal is to provide 100% Spec functionality (plus utility functionality where useful). At the very least, we should  split up the API call from parsing.

> What happens when [the `Fapi_GetInfo()` string] is not JSON? This code blows up.

You're right. That's very unfortunate because practically, this means you cannot ever use this string for anything programmatically without the risk of breaking things in the future. However, I need the contents of this string, e.g. because there is no better way to get the current FAPI profile name (which I need for testing). Any ideas how to go forward, here?

@williamcroberts  @AndreasFuchsSIT what do you think?

> @joholl and I also diverged in ESAPI vs FAPI function naming.

I also noticed that. There is an argument to be made for camel case: consistency with the spec. However, I'd rather go for _pythonic_-ness, that is adherence to the [python naming conventions](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names), i.e. snake case. @williamcroberts do you have a preference?

**Comment by IshFx** [comment]
> > What happens when [the `Fapi_GetInfo()` string] is not JSON? This code blows up.
> 
> You're right. That's very unfortunate because practically, this means you cannot ever use this string for anything programmatically without the risk of breaking things in the future. However, I need the contents of this string, e.g. because there is no better way to get the current FAPI profile name (which I need for testing). Any ideas how to go forward, here?
> 
> @williamcroberts @AndreasFuchsSIT what do you think?

How about exporting helper classes and let the user import them if he needs them ? This way the FAPI api stays clean and wont need to be updated if the string format changes.

**Comment by williamcroberts** [comment]
> > > What happens when [the `Fapi_GetInfo()` string] is not JSON? This code blows up.
> > 
> > 
> > You're right. That's very unfortunate because practically, this means you cannot ever use this string for anything programmatically without the risk of breaking things in the future. However, I need the contents of this string, e.g. because there is no better way to get the current FAPI profile name (which I need for testing). Any ideas how to go forward, here?
> > @williamcroberts @AndreasFuchsSIT what do you think?
> 
> How about exporting helper classes and let the user import them if he needs them (the helper class would expect the string to be in a defined format and throws an exception otherwise) ? This way the FAPI api stays clean and wont need to be updated if the string format changes.

That's kind of what I was thinking, just provide it as a separate utility class and just return the string from the FAPI call.

**Comment by williamcroberts** [comment]
The other thing I've noticed is the Fapi_Free calls in FAPI.py. Those should be assigned to the pointer as the deallocation routine, see: https://github.com/tpm2-software/tpm2-pytss/issues/165
