### ISSUE TITLE
Converge Naming

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-pytss#163]
Moved from #159.

> @joholl and I also diverged in ESAPI vs FAPI function naming. I went camelcase and @joholl went underscore. I'd also like to converge before release so the code base looks more consistent.

I also noticed that. There is an argument to be made for camel case: consistency with the spec. However, I'd rather go for _pythonic_-ness, that is adherence to the [python naming conventions](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names), i.e. snake case.

Also, we should align ESAPI vs Fapi. According to PEP 8, [python classes are camel case](https://www.python.org/dev/peps/pep-0008/#class-names).

@williamcroberts do you have a preference?

**Comment by williamcroberts** [comment]
- [ ] ESAPI PR #190
 - [ ] TCTI
 - [ ] TCTILdr
 - [ ] TSS2_Exception 
 - [ ] types
