### ISSUE TITLE
Support for tss2_fapi

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-pytss#17]
Add support for tss2_fapi.h / libtss2_fapi.so

@pdxjohnny Do you have some resources for this ?

**Comment by pdxjohnny** [comment]
Yes I'll get on this within the next few weeks

**Comment by pdxjohnny** [comment]
Started in #18

**Comment by pdxjohnny** [comment]
Done in 0.0.6
