### ISSUE TITLE
Possible missing swig directory in install dir?

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-pytss#20]
I have cloned the latest revision of tpm2-pytss and the built it using:

python3 setup.py build 

I then used the following command to install it:

python3 setup.py install --verbose --prefix=/usr

When I do this I then get an install directory that looks like this:

```
binding.py
_esys_binding.cpython-36m-x86_64-linux-gnu.so
_esys_binding.py
esys_binding.py
esys.py
exceptions.py
__init__.py
__pycache__
tcti.py
util
version.py
```

Running the following code 

```python
from tpm2_pytss.binding import *

def main():
        print("Hello world!")

if __name__ == "__main__":
    main()
```

then results in the ollowing error:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from tpm2_pytss.binding import *
  File "/usr/lib64/python3.6/site-packages/tpm2_pytss-0.0.3-py3.6-linux-x86_64.egg/tpm2_pytss/binding.py", line 417, in <module>
    TYPEDEFS = typedef_map()
  File "/usr/lib64/python3.6/site-packages/tpm2_pytss-0.0.3-py3.6-linux-x86_64.egg/tpm2_pytss/binding.py", line 409, in typedef_map
    for line in pkgutil.get_data(__name__.split(".")[0], "swig/tpm2_types.i")
  File "/usr/lib64/python3.6/pkgutil.py", line 634, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.6/site-packages/tpm2_pytss-0.0.3-py3.6-linux-x86_64.egg/tpm2_pytss/swig/tpm2_types.i'
```

In order to get things working I had to manually create the swig directory in the installation directory and copy the .i-files into it.

I wonder if this is bug or am I missing something?

**Comment by pdxjohnny** [comment]
Looks like we were missing `include_package_data`. Thank you!

**Comment by pdxjohnny** [comment]
@Superhepper New version is live. It should solve the issue Please let me know if it's still happening.

**Comment by Superhepper** [comment]
I cloned the repo today and tested it and I can confirm that this have been fixed.
