### ISSUE TITLE
tsskey.py is BSD-3 not BSD-2

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#222]
@whooo file https://github.com/tpm2-software/tpm2-pytss/blob/master/tpm2_pytss/tsskey.py shows as BSD-3 for SPDX but our LICENSE file is BSD-2, you OK with updating this to BSD-2?

**Comment by whooo** [comment]
Sure, I'll do a PR for it in a bit so the commit log will show my approval
