### ISSUE TITLE
FAPI.create_key does not set authPolicy for primary keys

### ISSUE THREAD

**Issue by gaetanww** [tpm2-software/tpm2-pytss#226]
`FAPI.create_key` won’t use the policy_path argument during key creation. See tpm2-tss [issue](https://github.com/tpm2-software/tpm2-tss/issues/2175)
To reproduce:
```python 
fapi.create_key('/HE/my-primary-key' 'system,sign,restricted', '/policy/my-policy')
blob = FAPI.get_tpm_blobs('/HE/my-primary-key')
assert(bytes(blob[0].publicArea.authPolicy.buffer) == b'')
```

**Comment by williamcroberts** [comment]
Fix was in external tpm2-tss libraries as referenced by https://github.com/tpm2-software/tpm2-tss/pull/2176
