### ISSUE TITLE
TSS2_Exception Complete

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#229]
Currently the TSS2_Exception class provides things like property "handle" or "session", but their is no way to know based on the format if you should ask for the handle, or the session, etc. So we should make what its referring to be discoverable... ie something like, where e is a TSS2_Exception in the fmt1 reponse....
```python
if e.is_fmt_1 and e.is_session_handle:
  print(f"Bad session {e.session}")
```
Or we need to think through the accessors better.

@whooo thoughts here since you put that together?

I think we want this interface at least thought through before 1.0 so we don't have to support or bump to 2.0.

**Comment by whooo** [comment]
> > It would be nice if we could pass the argument name and value with the exception, but that might be hard to get right.
> 
> Could you elaborate, i'm not picking up what you mean.

So for example if the exception says that parameter one has a bad value, for example a bad scheme,  passing the name of the argument (in_scheme) and possibly the actual value (TPMT_SIG_SCHEME(...)) via the exception could be useful.

**Comment by whooo** [comment]
I can always add a property called fmt1 so people can decide if the should check the other properties and ignore the name/value idea for now, so this doesn't hold the release back

**Comment by williamcroberts** [comment]
> I can always add a property called fmt1 so people can decide if the should check the other properties and ignore the name/value idea for now, so this doesn't hold the release back

That'd be good
