### ISSUE TITLE
Feature request: add attribute completion on objects such as TPM_OBJECT

### ISSUE THREAD

**Issue by niooss-ledger** [tpm2-software/tpm2-pytss#231]
Hello,
Currently there is no dynamic completion on objects returned by ESAPI calls. For example:

```python
>>> from tpm2_pytss import ESAPI, types
>>> esapi = ESAPI()
>>> esapi.get_capability(types.TPM2_CAP.TPM_PROPERTIES, 0)
(True, <tpm2_pytss.types.TPMS_CAPABILITY_DATA object at 0x7f4a51954340>)
>>> capdata = _[1]
>>> capdata.                    # press TAB
capdata.marshal(    capdata.unmarshal(  
>>> capdata.

# Nevertheless some fields exist
>>> capdata.capability
6
>>> capdata.data
<tpm2_pytss.types.TPMU_CAPABILITIES object at 0x7fdbe6a5ce80>
```

The current implementation uses `__getattributes__` to dynamically define attributes (and to dynamically convert objects between FFI and Python worlds): https://github.com/tpm2-software/tpm2-pytss/blob/8f9faf2b843e3ce7f8ded07456acf458f4f3890f/tpm2_pytss/types.py#L964

A simple way of making the completion work consists in implementing a `__dir__` method too, as described in https://docs.python.org/3/reference/datamodel.html#object.__dir__ and https://www.python.org/dev/peps/pep-0562/.

Currently:

```python
>>> dir(capdata)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__',
'__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__',
'__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__',
'__subclasshook__', '__weakref__', '_cdata', 'marshal', 'unmarshal']
```

With this patch:

```diff
--- a/tpm2_pytss/types.py
+++ b/tpm2_pytss/types.py
@@ -977,6 +977,9 @@
             obj = convert_to_python_native(globals(), x)
             return obj
 
+    def __dir__(self):
+        return object.__dir__(self) + dir(self._cdata)
+
     def __setattr__(self, key, value):
 
         _cdata = object.__getattribute__(self, "_cdata")
```

The `dir` result now contains `capability` and `data`:

```python
>>> dir(capdata)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__',
'__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__',
'__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__',
'__subclasshook__', '__weakref__', '_cdata', 'capability', 'data', 'marshal', 'unmarshal']
```

and the completion in the interactive interpreter works.

Could you please add `__dir__` methods for objects which define `__getattribute__` in [`tpm2_pytss/types.py`](https://github.com/tpm2-software/tpm2-pytss/blob/8f9faf2b843e3ce7f8ded07456acf458f4f3890f/tpm2_pytss/types.py)?

**Comment by williamcroberts** [comment]
Since everything inherits from TPM2B_OBJECT I think we can just add it there. See https://github.com/tpm2-software/tpm2-pytss/pull/233
