### ISSUE TITLE
support tools YAML output

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#235]
For things like tpm2b_public, support the YAML structured output of tools. Find ALL YAML outputs and have data type conversions for them via a to_yaml call.

**Comment by whooo** [comment]
I might take this on, it correlates to some other things I'm looking into

**Comment by whooo** [comment]
Closing as support was merged via https://github.com/tpm2-software/tpm2-pytss/pull/327
