### ISSUE TITLE
Missing swig directory in PyPI version 0.0.6 and 0.1.0

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-pytss#24]
The source tarballs from PyPI [`tpm2-pytss-0.0.6.tar.gz`](https://files.pythonhosted.org/packages/source/t/tpm2-pytss/tpm2-pytss-0.0.6.tar.gz) and [`tpm2-pytss-0.1.0.tar.gz`](https://files.pythonhosted.org/packages/source/t/tpm2-pytss/tpm2-pytss-0.1.0.tar.gz) are missing the `tpm2_pytss/swig` subdirectory. For version 0.0.5 this has been fixed by 8da58b34b20638057b44af1650c0ba52aef3cf46 (see #20), and [`tpm2-pytss-0.0.5.tar.gz`](https://files.pythonhosted.org/packages/source/t/tpm2-pytss/tpm2-pytss-0.0.5.tar.gz) is indeed fine, but apparently something changed again.

**Comment by pdxjohnny** [comment]
Damn it!!!

**Comment by pdxjohnny** [comment]
Thanks for reporting, I'll fix ASAP

**Comment by lukehinds** [comment]
Any plan to fix this still?

**Comment by pdxjohnny** [comment]
Sorry for the delay I got a bit tripped up by https://bugs.python.org/issue37247 but I figured out a wordaround. Should be working in the `0.1.2` release. @diabonas @lukehinds @williamcroberts

**Comment by pdxjohnny** [comment]
Let me know if it's not working for you

**Comment by diabonas** [comment]
I confirm that building from the PyPI sdist works again with version 0.1.2, thanks! One question, would it be possible to replace https://github.com/tpm2-software/tpm2-pytss/blob/e63d2349310ea380dec3b09cdf67601664f70a17/MANIFEST.in#L3
by
```
include tests/*.py
```
so that tests are distributed on PyPI as well? This is helpful if you want to run the test suite before installation, e.g. for distribution packaging. The line https://github.com/tpm2-software/tpm2-pytss/blob/e63d2349310ea380dec3b09cdf67601664f70a17/setup.py#L214 alone appears to be enough to avoid installing them to the site-packages directory (tested with both setuptools and pip).

I can create a PR if you want, but wanted to hear your motivation for including the `exclude` command first in case I am missing something here.

**Comment by diabonas** [comment]
Oh, and I noticed that 0.1.2 is not tagged in the Git repository, might be nice to do that here as well to keep in sync with the PyPI releases :)

**Comment by pdxjohnny** [comment]
@diabonas Only because I wasn't sure if `exclude=...` was enough. Thanks! Fixed in `0.1.3`

**Comment by diabonas** [comment]
Awesome, building and running the tests works with the 0.1.3 release downloaded from PyPI, cheers!
