### ISSUE TITLE
objects with friendly int fields should return the correct type

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-pytss#241]
For example, objectAttributes and type in a TPMT_PUBLIC should be a TPM2_ALG and a TPMA_OBJECT instance, not an ints

**Comment by williamcroberts** [comment]
Anything should return the right type

**Comment by williamcroberts** [comment]
@whooo isn't this fixed by PR #246 and we can close this?

**Comment by whooo** [comment]
> @whooo isn't this fixed by PR #246 and we can close this?

Not really, it's also about the right type for object fields, for example, getting sigAlg from a TPMT_SIGNATURE instance should return a TPM2_ALG, not an ordinary int.
As discussed in https://github.com/tpm2-software/tpm2-pytss/pull/240

**Comment by williamcroberts** [comment]
Ahh yes, I recall now. This was generating some type of type info so we can cast the int's back into their wrapper classes.
