### ISSUE TITLE
Should crypto methods like wrap go into crypto.py and not makecred.py

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#242]
So their are various crypto routines in makecred.py:
  - wrap
  - encrypt
  - hmac
  - generate_seed_<xxx>

Should these go to crypto.py?

With just make_cred left, should that just go to crypto as well and we can drop makecred.py?

@whooo  thoughs?

**Comment by whooo** [comment]
I think this can be closed now as it was part of the restructure
