### ISSUE TITLE
restructuring

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#248]
Thoughts on restructuring the code, current issues:
- Cyclic dependencies, for instance types and crypto. Crypto had to be dsigned to be type agnostic.
- Some things that should be "private" are not marked with an "_" prefix

Things to consider:
A package or module prefixed with an _ so we don't have to mark every function

**Comment by whooo** [comment]
How about a subdirectory called (_)internal for the private code?
And then:
* Move generate_seed, hmac and encrypt to crypto
* Move crypto to internals
* Move make_credential and wrap to a module called utils.py (which can container other smaller function/classes such as EK generation)
* Move all TPM_FRIENDLY_INT code to constants.py
