### ISSUE TITLE
Wrong return type `create_primary`

### ISSUE THREAD

**Issue by gaetanww** [tpm2-software/tpm2-pytss#252]
`ESAPI.create_primary` has the wrong return type:
[type hint](https://github.com/tpm2-software/tpm2-pytss/blob/master/tpm2_pytss/ESAPI.py#L4798) does not match [actual return value](https://github.com/tpm2-software/tpm2-pytss/blob/master/tpm2_pytss/ESAPI.py#L4880).

This kind of error could be spotted by mypy, is it worth running it in CI?

**Comment by williamcroberts** [comment]
Fixed by PR #258
