### ISSUE TITLE
Typing and documentation ESAPI.load_*

### ISSUE THREAD

**Issue by iolivergithub** [tpm2-software/tpm2-pytss#261]
In  load_external

def load(
        self,
        parent_handle: ESYS_TR,
        **in_private: TPM2B_SENSITIVE,**
        in_public: TPM2B_PUBLIC,
        session1: ESYS_TR = ESYS_TR.PASSWORD,
        session2: ESYS_TR = ESYS_TR.NONE,
        session3: ESYS_TR = ESYS_TR.NONE,
    ) -> ESYS_TR:

In the documentation this is shown as **TPM2B_PRIVATE**

**Comment by whooo** [comment]
Are we talking about load och load_external here? just to be sure.
But yes the documentation for load_external is slightly off.

**Comment by iolivergithub** [comment]
load_external

BTW, there is no example for load_external in the tests.  What should be used as the input to in_private ?

**Comment by whooo** [comment]
There is in test/test_crypto.py, all functions should have a test, but I agree that documentation is better, with that said, it's a good reference sometimes.
regarding the in_private argument, use None, perhaps it should be None by default, @williamcroberts, what do you say?

**Comment by iolivergithub** [comment]
BTW, tried to correct the documentation and was going to suggest the None option by default.  git push --set-upstream however reports permission denied.

**Comment by whooo** [comment]
did you fork the repo (on github that is) or do you try to push directly to this repo?
The usual workflow I follow is:
fork on github
pull your fork
create a branch and do a checkout on it
do the changes in that branch
push the branch, when doing that you will get a link to open a pull request

**Comment by iolivergithub** [comment]
Yeah, because I'm being exceptionally dumb today.  Changed pushed along with the above suggestion.  Load_External isn't mentioned in any tests so nothing will break with the change to the default values and parameter order.

**Comment by williamcroberts** [comment]
> Yeah, because I'm being exceptionally dumb today. Changed pushed along with the above suggestion. Load_External isn't mentioned in any tests so nothing will break with the change to the default values and parameter order.

A simple grep turns them up in test_crypto.py:
```
test_crypto.py:240:        handle = self.ectx.load_external(priv, pub)
test_crypto.py:245:            self.ectx.load_external(TPM2B_PUBLIC(), pub)
test_crypto.py:248:            self.ectx.load_external(priv, priv)
test_crypto.py:251:            self.ectx.load_external(priv, pub, 7467644)
test_crypto.py:254:            self.ectx.load_external(priv, pub, object)
test_crypto.py:257:            self.ectx.load_external(priv, pub, session1=76.5)
test_crypto.py:260:            self.ectx.load_external(priv, pub, session2=object())
test_crypto.py:263:            self.ectx.load_external(priv, pub, session3=TPM2B_PUBLIC())
test_crypto.py:306:        self.ectx.load_external(priv, pub, ESYS_TR.RH_NULL)
test_crypto.py:310:        self.ectx.load_external(None, pub, ESYS_TR.RH_NULL)
test_crypto.py:349:        handle = self.ectx.load_external(priv, pub, ESYS_TR.RH_NULL)
test_crypto.py:696:        handle = self.ectx.load_external(sens, pub, ESYS_TR.RH_NULL)
test_crypto.py:730:        self.ectx.load_external(sens, pub, ESYS_TR.RH_NULL)
test_crypto.py:757:        handle = self.ectx.load_external(sens, pub, ESYS_TR.RH_NULL)
```
