### ISSUE TITLE
from_pem should support string attributes

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#265]
It currently only supports the int/TPMA_OBJECT values, but it would be nice to have it support a string value and call TPMA_OBJECT.parse on behalf of the user.

**Comment by whooo** [comment]
perhaps we should support parse() on TPMT_SYM_DEF_OBJECT and TPMT_ASYM_SCHEME as well, so symmetric and scheme could be passed as strings as well.
