### ISSUE TITLE
TR_GetName returns TPM2B_NAME object with incorrect data

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-pytss#28]
When I am using tpm2_LoadExternal with a known key I get a name that is:
`000b9adccfa3d608ee3601a2bcb2ee29bd45ae6f3de9aa8be44b6379c118c9692217`

I then use the same key in the LoadExternal test. I use the following code to print the name of the key

```python
key_name_ptr_ptr = stack.enter_context(TPM2B_NAME_PTR_PTR())
self.esys_ctx.TR_GetName(object_handle, key_name_ptr_ptr)
key_name_ptr = key_name_ptr_ptr.value
key_name = to_bytearray(key_name_ptr.size, key_name_ptr.name)
print(binascii.b2a_hex(key_name))
```

But I get the following result:
`000b3268f9ca3e4af83e2547a933163a700f6580cf90d93abe8fb31afba129d2a682`

I was not really sure how to extract the data from key_name_ptr_ptr variable so the error may be that I am doing it incorrectly.

**Comment by Superhepper** [comment]
Maybe I should also point out that the keypair I am using for testing is a 2048 bit RSA key in PEM format.

**Comment by Superhepper** [comment]
I found the problem. TR_GetName was not to blame. I had provided TPMA_OBJECT_NODA as an objectAttribute which was incorrect.

**Comment by pdxjohnny** [comment]
Awesome! :D
