### ISSUE TITLE
Documentations of ESAPI.tr_deserialize and .tr_serialize are not formatted correctly

### ISSUE THREAD

**Issue by niooss-ledger** [tpm2-software/tpm2-pytss#291]
Hello,
On the page documenting `ESAPI` (https://tpm2-pytss.readthedocs.io/en/latest/esys.html), the documentation of methods `tr_deserialize` and `tr_serialize` is rendered in a way which does not seem right:

![tr_serialize](https://user-images.githubusercontent.com/64031241/146420582-2b35a721-303e-41ac-8fdb-e5c9be83ca39.jpg)

![tr_deserialize](https://user-images.githubusercontent.com/64031241/146420587-6c6f459d-aca2-4c2d-b74b-0dc341ae8cb0.jpg)

In the `Raises:` sections, there are dash signs (`- TypeError`) and the enumerations behind `TSS2_Exception` are formatted as a single entry.

I am not familiar enough with readthedocs to submit a Pull Request, but someone with more experience could take a look to find what is going wrong.

**Comment by williamcroberts** [comment]
https://github.com/tpm2-software/tpm2-pytss/pull/292
