### ISSUE TITLE
In crypto.py, why is sys.version_info compared as a float number?

### ISSUE THREAD

**Issue by niooss-ledger** [tpm2-software/tpm2-pytss#295]
Hello,
In the implementation of `_modinv`:
https://github.com/tpm2-software/tpm2-pytss/blob/7cd4cc0632f87b51483dc59630e7fb2d6abd2630/tpm2_pytss/internal/crypto.py#L241-L248

Why is `float(...)` used? Instead, it is possible to use a simple comparison such as:
```python
if sys.version_info < (3, 8):
    # ...
```
(In Python, comparing tuples work fine, and it uses the lexicographic order)

Moreover the current implementation makes the local variable `x` contain both the float representation of the Python version and the result of the extended GCD call. This makes type-checking more difficult and removing the first `x` using the suggested code above also makes type-checking the code easier. Would it be possible to modify this code?

**Comment by williamcroberts** [comment]
Yeah, I never even thought of comparing a tuple, that makes it much simpler.
