### ISSUE TITLE
Parsing output of PCR values from tpm2-tools

### ISSUE THREAD

**Issue by THS-on** [tpm2-software/tpm2-pytss#328]
The tpm2_quote command from tpm2-tools outputs a struct that is not a TPM data structure: https://github.com/tpm2-software/tpm2-tools/blob/fb4939ec0008720d1eae9be6d6c77cc80dd1f461/lib/pcr.h#L20-L24

It would be nice to read this structure directly with pytss to validate a quote generated with tpm2-tools.

**Comment by williamcroberts** [comment]
So it host endians the TPML_PCR_SELECTION, then specifies the count in host endianess, then for each TPML_DIGEST, host endians that and outputs the TPML_DIGEST... gross.

We can probably detect endianess by checking what count is, IIRC count should be limited to 24 (3 bytes of the select). If the number is stupid big when we convert it, we know we selected the wrong endianess.

**Comment by whooo** [comment]
I checked the source for tpm2_quote (see pcr_fwrite_serialized and pcr_fwrite_values in lib/pcr.c) and it support the output in two formats, only the digests (without size) and one which includes the PCR selections as well, the one with the selections uses little endian explicitly

**Comment by williamcroberts** [comment]
> I checked the source for tpm2_quote (see pcr_fwrite_serialized and pcr_fwrite_values in lib/pcr.c) and it support the output in two formats, only the digests (without size) and one which includes the PCR selections as well, the one with the selections uses little endian explicitly

Even more fun...

**Comment by williamcroberts** [comment]
Oh yeah it's host to le functions, I misread a lot of that, but at least its consistent so that makes that part easier, I was only looking at pcr_fwrite_serialized and didn't look at the pcr_fwrite_values that just dumps the digests sans selection.
