### ISSUE TITLE
Documentation on FAPI return codes

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-pytss#34]
@pdxjohnny I find these bindings really cool! However I do not understand the logic behind what is returned by the FAPI commands.

Example A) Fapi_GetRandom returns a `Swig Object of type 'TPMI_YES_NO *'` which can be casted into a `ByteArray` which we can iterate over to get the bytes

```python
            length = 32
            with UINT8_PTR_PTR() as random_uin8_ptr_ptr:
                random_swig = fapi_ctx.GetRandom(length, random_uin8_ptr_ptr)
                random_ByteArray = ByteArray.frompointer(random_swig)
                random_bytearray = bytearray(length)
                for i in range(0, length):
                    random_bytearray[i] = random_ByteArray[i]
                print(random_bytearray)
```

Example B) Fapi_GetInfo returns a `dict`

```python
            with CHAR_PTR_PTR() as info:
                cap = fapi_ctx.GetInfo(info)
                print(cap['capabilities'][1])
```

Example C) Fapi_List returns an `int`

```python
            with CHAR_PTR_PTR() as info:
                x = fapi_ctx.List("", info)
                print(x)
```

How can I access the actual list? I tried `print(CHAR_PTR.frompointer(x).value)` but gives me a segmentation fault. Is the `int` returned the TPM return code or something else?

And more generally: Is the return code of Fapi commands documented somewhere?

**Comment by pdxjohnny** [comment]
Hi @joholl! Thank you! I'm sorry for the confusion here. I have been struggling with the `CHAR_PTR` stuff myself. Here's a [video recording](https://www.youtube.com/watch?v=yAskW_jgfWk) of the issue. You'll see that it looks like SWIG is generating code which results in a double free. Hence the "segfault". That's as far as I've gotten with debugging it.

We could probably get around it by using the bytearray stuff and then casting to a `str`...

As for FAPI documentation, the spec is here: https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0.94_r04_pubrev.pdf

I personally use the [TPM2-TSS FAPI tests](https://github.com/tpm2-software/tpm2-tss/tree/master/test/integration) as a guide sometimes

Let me know if you run into anything else. Others are also more well versed then me about FAPI and ESAPI workings, they usually hang out on the mailing list or the gitter channel https://github.com/tpm2-software/tpm2-tss#getting-in-touch

**Comment by pdxjohnny** [comment]
We might want to change the title of this issue to reflect the `CHAR_PTR` issue, as I must have forgetten to make one

**Comment by joholl** [comment]
I digged into this some more. I'm not sure if there is a bug with `CHAR_PTR` but if so, it did not cause my problems.

The C FAPI commands return a status code of type `TSS2_RC`. All data is returned via the parameters (non-const pointers for fixed-size types and double pointers otherwise).

The python wrapper for the Fapi functions, on the other hand, does not return a status code, but the parameters which return data to the user. I attached the relevant code snipped at the end. Basically, we iterate over all parameters (except the `fapi_context`):

* only for non-`const` pointer parameters:
    * if `char **`: this is a pointer to a string
         * if it seems to be JSON: try to decode it and add it to the return list
         * else (missing): **do nothing, this is the bug**
    * elif `... **`: this is a pointer to a byte string
         * if this param is `uint8_t **` and the next param is `size_t *`, convert the byte string into a `ByteArray` and add it to the return list
         * else: add this parameter to the return list
    * else: add this parameter to the return list

Now `Fapi_List` returns a string. However, since it is not JSON, it is ignored and not returned to the user. This should fix the issue:

```diff
diff --git a/tpm2_pytss/context.py b/tpm2_pytss/context.py
index cc26b12..c9a3445 100644
--- a/tpm2_pytss/context.py
+++ b/tpm2_pytss/context.py
@@ -127,6 +127,8 @@ class BaseContextMetaClass(type):
                                 return_value.append(json.loads(value.value))
                             except json.decoder.JSONDecodeError:
                                 return_value.append(value.value)
+                        else:
+                            return_value.append(value.value)
                     elif "**" in docstring.split():
                         if (i + 1) < len(docstring_arguments):
                             next_docstring = docstring_arguments[i + 1]
```

Furthermore, there should probably be some documentation describing what the bindings return to the user. The [doc on the github pages](https://tpm2-software.github.io/tpm2-pytss/fapi.html) lists the C-style return values (which appears wrong to me).

https://github.com/tpm2-software/tpm2-pytss/blob/04c057ce767ced60f58b65efa9600d3b8234cada/tpm2_pytss/context.py#L117-L146

**Comment by pdxjohnny** [comment]
Ah I understand. Sorry I did the updates for return values and didn't finish the test for them. Damn! Thank you for pointing this out

**Comment by joholl** [comment]
No problem. We might also consider returning `None`. For example the simulator does not have a certificate. `GetCertificate` should probably return `None` in this case.

```python
with CHAR_PTR_PTR() as x509certData:
     ret = fapi_ctx.GetCertificate("", x509certData)
     print(ret)
```

This should fix it. Maybe other branches should be able to deal with `None`, too?

```diff
             skip = False
             for i, (value, docstring) in enumerate(zip(args, docstring_arguments)):
                 if skip:
                     skip = False
                     continue
                 if not "const" in docstring.split() and "*" in docstring:
                     # char ** arguments are always guaranteed to be NULL
                     # terminated
                     if docstring.startswith("char") and "**" in docstring.split():
-                        if any(map(value.value.startswith, ["[", "{"])):
+                        if value.value is None:
+                            return_value.append(None)
+                        elif any(map(value.value.startswith, ["[", "{"])):
                             try:
                                 return_value.append(json.loads(value.value))
                             except json.decoder.JSONDecodeError:
                                 return_value.append(value.value)
```

**Comment by pdxjohnny** [comment]
Thanks for digging around with this. I've applied those two diffs as https://github.com/tpm2-software/tpm2-pytss/commit/beb40175ac145f41e530d2cefa10b6e271191045 and released a new version

**Comment by joholl** [comment]
No problem. We might also consider returning `None`. For example the simulator does not have a certificate. `GetCertificate` should probably return `None` in this case.

```python
with CHAR_PTR_PTR() as x509certData:
     ret = fapi_ctx.GetCertificate("", x509certData)
     print(ret)
```

This should fix it. Maybe other branches should be able to deal with `None`, too?

```diff
             skip = False
             for i, (value, docstring) in enumerate(zip(args, docstring_arguments)):
                 if skip:
                     skip = False
                     continue
                 if not "const" in docstring.split() and "*" in docstring:
                     # char ** arguments are always guaranteed to be NULL
                     # terminated
                     if docstring.startswith("char") and "**" in docstring.split():
-                        if any(map(value.value.startswith, ["[", "{"])):
+                        if value.value is None:
+                            return_value.append(None)
+                        elif any(map(value.value.startswith, ["[", "{"])):
                             try:
                                 return_value.append(json.loads(value.value))
                             except json.decoder.JSONDecodeError:
                                 return_value.append(value.value)
```

**Comment by joholl** [comment]
Thanks for fixing the issue so fast!
