### ISSUE TITLE
Successful install via pip3,  errors during import

### ISSUE THREAD

**Issue by iolivergithub** [tpm2-software/tpm2-pytss#342]
Might be related to #341 ?

$ cat /etc/issue
Ubuntu 20.04.4 LTS \n \l
$ python3 --version
Python 3.8.10

$ sudo pip3 install tpm2-pytss
Collecting tpm2-pytss
  Downloading tpm2-pytss-1.1.0.tar.gz (163 kB)
     |████████████████████████████████| 163 kB 14.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting asn1crypto
  Using cached asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from tpm2-pytss) (2.8)
Collecting cffi>=1.0.0
  Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting pkgconfig
  Using cached pkgconfig-1.5.5-py3-none-any.whl (6.7 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: tpm2-pytss
  Building wheel for tpm2-pytss (PEP 517) ... done
  Created wheel for tpm2-pytss: filename=tpm2_pytss-1.1.0-cp38-cp38-linux_x86_64.whl size=835446 sha256=6649ef798d93730fde137c23eadd96018aa76dfafbd4663fdb93d3832362aa31
  Stored in directory: /root/.cache/pip/wheels/9a/d8/be/6263b9c88f159908a2c262150bb127846ee2a546412d359750
Successfully built tpm2-pytss
Installing collected packages: asn1crypto, pycparser, cffi, pkgconfig, tpm2-pytss
Successfully installed asn1crypto-1.5.1 cffi-1.15.0 pkgconfig-1.5.5 pycparser-2.21 tpm2-pytss-1.1.0

$ python3 xxx.py 
<<irrelevant debug output here>>>
Traceback (most recent call last):
  File "u10.py", line 16, in <module>
    from blueprints.protocols import protocols_blueprint
  File "/home/ioliver/AttestationEngine/u10/blueprints/protocols.py", line 12, in <module>
    import a10.asvr.protocols.protocol_dispatcher
  File "/usr/local/lib/python3.8/dist-packages/a10server-2022.4.13-py3.8.egg/a10/asvr/protocols/protocol_dispatcher.py", line 11, in <module>
    import a10.asvr.protocols.A10tpm2send
  File "/usr/local/lib/python3.8/dist-packages/a10server-2022.4.13-py3.8.egg/a10/asvr/protocols/A10tpm2send.py", line 12, in <module>
    from tpm2_pytss import *
  File "/usr/local/lib/python3.8/dist-packages/tpm2_pytss/__init__.py", line 2, in <module>
    from .ESAPI import ESAPI
  File "/usr/local/lib/python3.8/dist-packages/tpm2_pytss/ESAPI.py", line 2, in <module>
    from .types import *
  File "/usr/local/lib/python3.8/dist-packages/tpm2_pytss/types.py", line 23, in <module>
    from tpm2_pytss.internal.crypto import (
  File "/usr/local/lib/python3.8/dist-packages/tpm2_pytss/internal/crypto.py", line 9, in <module>
    from cryptography.hazmat.primitives.serialization import (
ImportError: cannot import name 'load_ssh_private_key' from 'cryptography.hazmat.primitives.serialization' (/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/__init__.py)

The code referred to above  (ie: line 12 in A10tpm2send.py" - line 13 also):

from tpm2_pytss import *
from tpm2_pytss.utils import *

**Comment by whooo** [comment]
What version of python3-cryptography do you have installed on the system?

**Comment by iolivergithub** [comment]
$ pip install cryptography
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (2.8)
ioliver@covid19:/usr/local/lib/python3.8/dist-packages$ sudo pip3 install cryptography
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (2.8)

**Comment by iolivergithub** [comment]
$ python3 -m pip install -U cryptography
Collecting cryptography
  Downloading cryptography-36.0.2-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 29.7 MB/s 
Requirement already satisfied, skipping upgrade: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography) (1.15.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography) (2.21)
Installing collected packages: cryptography
Successfully installed cryptography-36.0.2


Now works.

**Comment by whooo** [comment]
We should probably set a minimum version requirement for cryptography in setup.cfg

**Comment by iolivergithub** [comment]
Can confirm that v36 of cryptography works.

**Comment by whooo** [comment]
Ubuntu 22.04 seems to have 2.8 by default, which explains your error at least, I'll add a required version when I fix some other things
