### ISSUE TITLE
Question regarding code usage

### ISSUE THREAD

**Issue by terilenard** [tpm2-software/tpm2-pytss#354]
Are there available code examples/snippets on how to use tpm2-pytss with a real tpm not simulated? From what I saw so far there are only the tests available as a starting point for using the library.

Thank you!

**Comment by whooo** [comment]
There is https://github.com/tpm2-software/tpm2-pytss/pull/317 which contains some basic examples for some of the supported APIs and most of the APIs are pythonic versions of the TPM software stack specifications which might be helpful.
Generally speaking the only difference between a TPM simulator and a real TPM is that the simulator is missing the endorsement certificate but probably support more algorithms and operations so most of the tests should work on a real TPM as well

**Comment by terilenard** [comment]
@whooo Thank you for the link. Will have a look. :)

Teri.

**Comment by williamcroberts** [comment]
Yeah it's really all in the setup, So either your FAPI config passed to the FAPI constructor or the parameters to the call to ESAPI.
