### ISSUE TITLE
Installation issues on fresh RHEL8.6 VM 

### ISSUE THREAD

**Issue by GastonMeghi** [tpm2-software/tpm2-pytss#373]
I'm trying to test the library and I've noticed that the installation fails in a fresh RHEL8.6 VM. 

From the [documentation](https://tpm2-pytss.readthedocs.io/en/latest/install.html#pip-install), the installation steps should be:

(I took the steps for Fedora32 since it's the closest to RHEL8.6)
dnf update
dnf install tpm2-tss-devel
python3 -m pip install tpm2-pytss

But the installation fails. 

Steps to reproduce:
Fresh RHEL 8.6 VM
dnf update
dnf install tpm2-tss-devel
python3 -m pip install tpm2-pytss

If we could get this package appropriately for RHEL as well it would be awesome!

Result:

```
[root@localhost ~]# dnf update
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   14 MB/s |  52 MB     00:03    
Red Hat Enterprise Linux 8 for x86_64 - AppStre  18 MB/s |  47 MB     00:02    
Last metadata expiration check: 0:00:05 ago on vie 21 oct 2022 14:18:00 -03.
Dependencies resolved.
================================================================================
 Package   Arch     Version            Repository                          Size
================================================================================
Upgrading:
 firefox   x86_64   102.4.0-1.el8_6    rhel-8-for-x86_64-appstream-rpms   108 M
 tzdata    noarch   2022e-1.el8        rhel-8-for-x86_64-baseos-rpms      471 k

Transaction Summary
================================================================================
Upgrade  2 Packages

Total download size: 109 M
Is this ok [y/N]: y
Is this ok [y/N]: y
Downloading Packages:
(1/2): tzdata-2022e-1.el8.noarch.rpm            581 kB/s | 471 kB     00:00    
(2/2): firefox-102.4.0-1.el8_6.x86_64.rpm        20 MB/s | 108 MB     00:05    
--------------------------------------------------------------------------------
Total                                            20 MB/s | 109 MB     00:05     
Red Hat Enterprise Linux 8 for x86_64 - BaseOS  4.9 MB/s | 5.0 kB     00:00    
Importing GPG key 0xFD431D51:
 Userid     : "Red Hat, Inc. (release key 2) <security@redhat.com>"
 Fingerprint: 567E 347A D004 4ADE 55BA 8A5F 199E 2F91 FD43 1D51
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
Is this ok [y/N]: y
Key imported successfully
Importing GPG key 0xD4082792:
 Userid     : "Red Hat, Inc. (auxiliary key) <security@redhat.com>"
 Fingerprint: 6A6A A7C9 7C88 90AE C6AE BFE2 F76F 66C3 D408 2792
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Upgrading        : firefox-102.4.0-1.el8_6.x86_64                         1/4 
  Running scriptlet: firefox-102.4.0-1.el8_6.x86_64                         1/4 
  Upgrading        : tzdata-2022e-1.el8.noarch                              2/4 
  Cleanup          : tzdata-2022d-1.el8.noarch                              3/4 
  Running scriptlet: firefox-102.3.0-6.el8_6.x86_64                         4/4 
  Cleanup          : firefox-102.3.0-6.el8_6.x86_64                         4/4 
  Running scriptlet: firefox-102.3.0-6.el8_6.x86_64                         4/4 
  Running scriptlet: firefox-102.4.0-1.el8_6.x86_64                         4/4 
  Running scriptlet: firefox-102.3.0-6.el8_6.x86_64                         4/4 
  Verifying        : tzdata-2022e-1.el8.noarch                              1/4 
  Verifying        : tzdata-2022d-1.el8.noarch                              2/4 
  Verifying        : firefox-102.4.0-1.el8_6.x86_64                         3/4 
  Verifying        : firefox-102.3.0-6.el8_6.x86_64                         4/4 
Installed products updated.

Upgraded:
  firefox-102.4.0-1.el8_6.x86_64            tzdata-2022e-1.el8.noarch           

Complete!
[root@localhost ~]# dnf install tpm2-tss-devel
Updating Subscription Management repositories.
Last metadata expiration check: 0:00:50 ago on vie 21 oct 2022 14:18:00 -03.
Dependencies resolved.
================================================================================
 Package          Arch     Version        Repository                       Size
================================================================================
Installing:
 tpm2-tss-devel   x86_64   2.3.2-4.el8    rhel-8-for-x86_64-baseos-rpms   242 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 242 k
Installed size: 514 k
Is this ok [y/N]: y
Downloading Packages:
tpm2-tss-devel-2.3.2-4.el8.x86_64.rpm           139 kB/s | 242 kB     00:01    
--------------------------------------------------------------------------------
Total                                           139 kB/s | 242 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : tpm2-tss-devel-2.3.2-4.el8.x86_64                      1/1 
  Running scriptlet: tpm2-tss-devel-2.3.2-4.el8.x86_64                      1/1 
  Verifying        : tpm2-tss-devel-2.3.2-4.el8.x86_64                      1/1 
Installed products updated.

Installed:
  tpm2-tss-devel-2.3.2-4.el8.x86_64                                             

Complete!
[root@localhost ~]# python3 -m pip install tpm2-pytss
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting tpm2-pytss
  Downloading https://files.pythonhosted.org/packages/b8/ac/35e2e7cd75f1a5a79a28207cde23d08850f0a700512e6144c0ce916cb648/tpm2-pytss-1.2.0.tar.gz (178kB)
    100% |████████████████████████████████| 184kB 6.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tqj1b0uo/tpm2-pytss/setup.py", line 6, in <module>
        from pkgconfig import pkgconfig
    ModuleNotFoundError: No module named 'pkgconfig'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tqj1b0uo/tpm2-pytss/
[root@localhost ~]# python3 -m pip install pkgconfig
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting pkgconfig
  Downloading https://files.pythonhosted.org/packages/32/af/89487c7bbf433f4079044f3dc32f9a9f887597fe04614a37a292e373e16b/pkgconfig-1.5.5-py3-none-any.whl
Installing collected packages: pkgconfig
Successfully installed pkgconfig-1.5.5
[root@localhost ~]# python3 -m pip install tpm2-pytss
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting tpm2-pytss
  Using cached https://files.pythonhosted.org/packages/b8/ac/35e2e7cd75f1a5a79a28207cde23d08850f0a700512e6144c0ce916cb648/tpm2-pytss-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cm1l87o8/tpm2-pytss/setup.py", line 7, in <module>
        from pycparser import c_parser, preprocess_file
    ModuleNotFoundError: No module named 'pycparser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cm1l87o8/tpm2-pytss/
```

**Comment by williamcroberts** [comment]
I think we need pycparser added to our deps:
```diff
diff --git a/setup.cfg b/setup.cfg
index 5426a07c3ca9..7898be5955d4 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -30,6 +30,7 @@ setup_requires =
     cryptography>=3.0
     asn1crypto
     packaging
+    pycparser
 install_requires =
     cffi>=1.0.0
     asn1crypto
```

can you try installing `pycparser`:
```bash
pip install pycparser
```
and then install tpm2-pytss and see if it works?

**Comment by whooo** [comment]
cffi should depend on pycparser, but that might be a new thing, might be good to have a explicit depend tho.
RHEL8 might have a tpm2-tss stack that is to old as well, I might be wrong but I recall there being issues with running it with anything older then 2.4.0

**Comment by williamcroberts** [comment]
> cffi should depend on pycparser, but that might be a new thing, might be good to have a explicit depend tho.

We explicitly import pycparser, so I think we should have an explicit depends and not rely on that behavior.

> RHEL8 might have a tpm2-tss stack that is to old as well, I might be wrong but I recall there being issues with running it with anything older then 2.4.0

2.4.0 is the minimum supported version and is mentioned in the README, however, we don't have all the explicit checks in scripts/libtss2_build.py, we probably should add those:
```diff
diff --git a/scripts/libtss2_build.py b/scripts/libtss2_build.py
index 938fb786a6e2..d618733f6049 100644
--- a/scripts/libtss2_build.py
+++ b/scripts/libtss2_build.py
@@ -26,12 +26,12 @@ def get_include_paths(library_names):
 
 libraries = ["tss2-esys", "tss2-tctildr", "tss2-rc", "tss2-mu"]
 
-if not pkgconfig.installed("tss2-esys", ">=2.0.0"):
-    raise RuntimeError("Require tss2-esapi to be installed and at least version 2.0.0")
+if not pkgconfig.installed("tss2-esys", ">=2.4.0"):
+    raise RuntimeError("Require tss2-esapi to be installed and at least version 2.4.0")
 
 # Needs some missing marshal routines like Tss2_MU_TPMU_ENCRYPTED_SECRET_Marshal
 if not pkgconfig.installed("tss2-mu", ">=2.4.0"):
-    raise RuntimeError("Require tss2-mu to be installed")
+    raise RuntimeError("Require tss2-mu 2.4.0 or greater to be installed")
 
 if not pkgconfig.exists("tss2-tctildr"):
     raise RuntimeError("Require tss2-tctildr to be installed")
```

**Comment by GastonMeghi** [comment]
Thank you for your fast reply!

> 2.4.0 is the minimum supported version and is mentioned in the README

I didn't notice that. And it seems that tpm2-tss-devel-2.3.2-4.el8.x86_64 is the latest one packaged for RHEL8.6 

So I tried with RHEL9, but I didn't have much luck either. I have tpm2-tss.x86_64 version 3.0.3-7.el9 packaged but not tpm2-tss-devel

`[admin@localhost ~]$ sudo dnf update
[sudo] password for admin: 
Updating Subscription Management repositories.
Last metadata expiration check: 0:20:42 ago on Fri 21 Oct 2022 04:45:32 PM -03.
Dependencies resolved.
Nothing to do.
Complete!
[admin@localhost ~]$ sudo dnf install tpm2-tss-devel
Updating Subscription Management repositories.
Last metadata expiration check: 0:20:55 ago on Fri 21 Oct 2022 04:45:32 PM -03.
No match for argument: tpm2-tss-devel
Error: Unable to find a match: tpm2-tss-devel
[admin@localhost ~]$ sudo dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/tpm2-tss-devel-1.4.0-3.el7.x86_64.rpm
Updating Subscription Management repositories.
Last metadata expiration check: 0:23:17 ago on Fri 21 Oct 2022 04:45:32 PM -03.
tpm2-tss-devel-1.4.0-3.el7.x86_64.rpm                                                                                  72 kB/s |  55 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides libsapi.so.0()(64bit) needed by tpm2-tss-devel-1.4.0-3.el7.x86_64
  - nothing provides libtcti-device.so.0()(64bit) needed by tpm2-tss-devel-1.4.0-3.el7.x86_64
  - nothing provides libtcti-socket.so.0()(64bit) needed by tpm2-tss-devel-1.4.0-3.el7.x86_64
  - nothing provides tpm2-tss(x86-64) = 1.4.0-3.el7 needed by tpm2-tss-devel-1.4.0-3.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[admin@localhost ~]$ sudo dnf install https://www.rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/tpm2-tss-devel-3.0.3-8.el9.x86_64.rpm
Updating Subscription Management repositories.
Last metadata expiration check: 0:24:57 ago on Fri 21 Oct 2022 04:45:32 PM -03.
tpm2-tss-devel-3.0.3-8.el9.x86_64.rpm                                                                                 135 kB/s | 351 kB     00:02    
Error: 
 Problem: conflicting requests
  - nothing provides pkgconfig(json-c) needed by tpm2-tss-devel-3.0.3-8.el9.x86_64
  - nothing provides tpm2-tss(x86-64) = 3.0.3-8.el9 needed by tpm2-tss-devel-3.0.3-8.el9.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[admin@localhost ~]$ dnf list installed | grep tpm
tpm2-tools.x86_64                                5.0-10.el9                       @anaconda                        
tpm2-tss.x86_64                                  3.0.3-7.el9                      @anaconda                        
[admin@localhost ~]$ ^C
[admin@localhost ~]$ python3 -m pip install tpm2-pytss
Defaulting to user installation because normal site-packages is not writeable
Collecting tpm2-pytss
  Downloading tpm2-pytss-1.2.0.tar.gz (178 kB)
     |################################| 178 kB 4.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_yfj2v6k
         cwd: /tmp/pip-install-f_hugti7/tpm2-pytss_6cb453a80f944682879e440343145538
    Complete output (33 lines):
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 237, in <module>
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
        _Distribution.__init__(
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 900, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-_r4kyaui/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-_r4kyaui/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-_r4kyaui/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-_r4kyaui/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "scripts/libtss2_build.py", line 30, in <module>
        raise RuntimeError("Require tss2-esapi to be installed and at least version 2.0.0")
    RuntimeError: Require tss2-esapi to be installed and at least version 2.0.0
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b8/ac/35e2e7cd75f1a5a79a28207cde23d08850f0a700512e6144c0ce916cb648/tpm2-pytss-1.2.0.tar.gz#sha256=3a05964e3723dd0778752682c18f9fb914292d2167e3ef68d7590f47d9fc6b9e (from https://pypi.org/simple/tpm2-pytss/). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_yfj2v6k Check the logs for full command output.
  Downloading tpm2-pytss-1.1.0.tar.gz (163 kB)
     |################################| 163 kB 44.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzco2avbo
         cwd: /tmp/pip-install-f_hugti7/tpm2-pytss_4b77be80402e4e55b78f08d9877d7539
    Complete output (33 lines):
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 232, in <module>
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
        _Distribution.__init__(
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 900, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-ey29j6q7/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-ey29j6q7/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-ey29j6q7/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-ey29j6q7/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "scripts/libtss2_build.py", line 30, in <module>
        raise RuntimeError("Require tss2-esapi to be installed and at least version 2.0.0")
    RuntimeError: Require tss2-esapi to be installed and at least version 2.0.0
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b5/bd/92b4cbb46f730c82f074d01d60f8dc2a816c4b72fed9d3dc2a45eed3af5f/tpm2-pytss-1.1.0.tar.gz#sha256=3b47756fdf7f57c6f77a66e0f2f79ead3ac919255bfe9ae53d56fba921c4add4 (from https://pypi.org/simple/tpm2-pytss/). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzco2avbo Check the logs for full command output.
  Downloading tpm2-pytss-1.0.0.tar.gz (145 kB)
     |################################| 145 kB 10.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmplvm0moki
         cwd: /tmp/pip-install-f_hugti7/tpm2-pytss_f927ffc3c7a940378c85360553c0196b
    Complete output (33 lines):
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 196, in <module>
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
        _Distribution.__init__(
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 900, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-c_mm6j86/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-c_mm6j86/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-c_mm6j86/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-c_mm6j86/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "scripts/libtss2_build.py", line 30, in <module>
        raise RuntimeError("Require tss2-esapi to be installed and at least version 2.0.0")
    RuntimeError: Require tss2-esapi to be installed and at least version 2.0.0
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/cb/2bcf957f7f593a39c9ac231fa1afbf5895c441b98779d76600e5f8123aa3/tpm2-pytss-1.0.0.tar.gz#sha256=1b1d6721762e853990bdaf4b9ad4d8bddd67c911ffa41419e5b27c38b71cd65a (from https://pypi.org/simple/tpm2-pytss/). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmplvm0moki Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tpm2-pytss (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.5, 0.0.6, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.1.0rc0, 1.1.0rc1, 1.1.0, 1.2.0)
ERROR: No matching distribution found for tpm2-pytss
[admin@localhost ~]$ 
`

**Comment by whooo** [comment]
If you don't have the development package installed you wont be able to build the bindings.
IIRC RHEL9 (and possibly RHEL8 as well) have been split up amongst different repositories, check that you have the right ones enabled according to  https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/package_manifest/index

Also, if you put  ``` around the logs they will be more readable
