### ISSUE TITLE
Some TPM2B types should be bytes-like

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-pytss#39]
It would be useful if the TPM2B structures that just has a size and a series of bytes would be bytes-like.
For example, the output from NV_Read is a TPM2B_MAX_NV_BUFFER should behave like a bytes object.

**Comment by pdxjohnny** [comment]
Will do

**Comment by williamcroberts** [comment]
Switched to CFFI bindings, where the returns are more Pythonic and expected data types.
