### ISSUE TITLE
ImportError - undefined symbol: Esys_MAC_Start_Async

### ISSUE THREAD

**Issue by l-sousa** [tpm2-software/tpm2-pytss#392]
After installing/compiling everything for pytss i run into the error:

`ImportError: /usr/local/lib/python3.9/dist-packages/tpm2_pytss/_libtpm2_pytss.abi3.so: undefined symbol: Esys_MAC_Start_Async`

I don't know how this could happen. I've already checked the source code and the symbol is there (although I've installed from pip, but I think it doesn't make a difference). 

It happens on all tests under /test in this repo.

**Comment by williamcroberts** [comment]
What version of tpm2-tss do you have installed, it must be from the master branch?

**Comment by williamcroberts** [comment]
> What version of tpm2-tss do you have installed, it must be from the master branch?

What's your distro as well? My guess is that it's building against the new headers but linking against an old ESAPI. On ubuntu 22.04 things are starting to depend on tss2-esys and it has a priority linking order as things under this path usually are pulled before standard /usr/lib:
  - /usr/lib/x86_64-linux-gnu/libtss2-esys.so.0.0.0

Can you see if you have an tss2-esys.so floating around other than the one you built off of master with?

**Comment by l-sousa** [comment]
> What version of tpm2-tss do you have installed, it must be from the master branch?

`
tpm-quote-tools/stable 1.0.4-1 armhf
tpm-tools-pkcs11/stable 1.3.9.1-0.2 armhf
tpm-tools/stable 1.3.9.1-0.2 armhf
tpm-udev/stable,now 0.5 all [installed,automatic]
tpm2-abrmd/stable 2.3.3-1+b1 armhf
tpm2-initramfs-tool/stable 0.2.2-2 armhf
tpm2-tools/stable,now 5.0-2 armhf [installed]
`

Distro is raspian, it's a rpi :)

**Comment by l-sousa** [comment]
The only libtss2-esys.so I have are these two
/usr/lib/arm-linux-gnueabihf/libtss2-esys.so.0.0.0
/usr/lib/arm-linux-gnueabihf/libtss2-esys.so.0

**Comment by williamcroberts** [comment]
> The only libtss2-esys.so I have are these two /usr/lib/arm-linux-gnueabihf/libtss2-esys.so.0.0.0 /usr/lib/arm-linux-gnueabihf/libtss2-esys.so.0

Whats the tss version?

**Comment by l-sousa** [comment]
> Whats the tss version?

from the git repo - 3.2.0

**Comment by l-sousa** [comment]
I mean, not sure, I don't remember if I installed this one from the repo or apt... sorry long day... 

libtss-dev/stable,now 1045-1.2+b1 armhf [installed]
libtss0/stable,now 1045-1.2+b1 armhf [installed,automatic]
libtss2-dev/stable 3.0.3-2 armhf
libtss2-esys-3.0.2-0/stable,now 3.0.3-2 armhf [installed]
libtss2-fapi1/stable 3.0.3-2 armhf
libtss2-mu0/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-rc0/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-sys1/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-tcti-cmd0/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-tcti-device0/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-tcti-mssim0/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-tcti-swtpm0/stable,now 3.0.3-2 armhf [installed,automatic]
libtss2-tcti-tabrmd-dev/stable 2.3.3-1+b1 armhf
libtss2-tcti-tabrmd0/stable 2.3.3-1+b1 armhf
libtss2-tctildr0/stable,now 3.0.3-2 armhf [installed,automatic]

it's tss 3.0.3?

**Comment by williamcroberts** [comment]
>> Whats the tss version?
> from the git repo - 3.2.0

Something is not in that state. `Esys_MAC*` routines are only on master. My guess is that the headers are on master and the linked library is not. Without ssh'ing into your machine, you'll have to dig up as to why.

**Comment by l-sousa** [comment]
I'm going to email you if that's ok

**Comment by whooo** [comment]
What content do you have in /usr/local/lib/python3.9/dist-packages/tpm2_pytss/internal/versions.py ?

**Comment by l-sousa** [comment]
> What content do you have in /usr/local/lib/python3.9/dist-packages/tpm2_pytss/internal/versions.py ?

"tss2-esys": "3.2.0-151-g10a5e226",
"tss2-fapi": "3.2.0-151-g10a5e226",

**Comment by whooo** [comment]
So built against master, when you say:
"After installing/compiling everything for pytss i run into the error:" which steps are you talking about?

**Comment by nickbedbury** [comment]
I assume the latest tagged release (`3.2.0` right now) should be used to compile `tpm2-tss` from source instead of `master`?  

It's not clear based on the above comments.

Thanks

**Comment by whooo** [comment]
master should be supported, but the runtime libraries should be the same (or newer) as the build time libraries, so if you build again tpm2-tss master, make sure your environment uses the libraries produced by tpm2-tss master, not for example the distro packages

**Comment by nickbedbury** [comment]
This worked for me (without a rebuild of `tpm2-tss`):
```
$ export LD_LIBRARY_PATH=/usr/local/lib
$ python3
Python 3.9.6 (default, Sep 30 2022, 04:43:22) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tpm2_pytss
>>>
```

The distro libraries are in `/usr/lib/`, whereas the built libraries are in `/usr/local/lib/`

**Comment by williamcroberts** [comment]
Looks like we can close this?

**Comment by l-sousa** [comment]
I haven't been able to work on this recently. For the sake of cleaning issues, sure, you can close. Otherwise you can just leave it open and I'll update you when I can...

**Comment by williamcroberts** [comment]
I'll leave it open, let me know if you get stuck. My guess is still different versions of library .so's kicking around

**Comment by l-sousa** [comment]
That was the problem: outdated tpm2-tss install from apt. Compiling from source fixed this.
