### ISSUE TITLE
TPML types should be iterable and indexable

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-pytss#40]
It would be useful if all the TPML types could iterable and perhaps indexable.
A good example is getting all the digests from a call to PCR_Read.

**Comment by williamcroberts** [comment]
I'm just trying to figure out why we're handling types like this. I don't see why the types need to be handled with a context manager, when they could just free their allocated resource on `__del__` and let the normal garbage collection mechanism deal with free'ing things.

If I just look at FAPI example, I would imagine it's simplest should be:
```python
# default config
fapi = FAPI()

# arguments default to None, None, None
fapi.Provision()

value = fapi_ctx.GetRandom(length)

# Fapi goes out of scope, reference count hits 0, __del__ is invoked, teardown is performed.
```

We probably have to write a lot more python between the API and the C library, but this seems worth the effort to make the caller code simplest.

**Comment by williamcroberts** [comment]
Hrm, Ill have to keep this bug in mind as I expand the ESAPI bindings.

**Comment by williamcroberts** [comment]
@whoo I think I have this complete. If you look at the current TPML_ tests in test_types you'll see both index tests as well as iteration tests once PR https://github.com/tpm2-software/tpm2-pytss/pull/87 is complete. Do you agree?
