### ISSUE TITLE
Provide way to scrub memory

### ISSUE THREAD

**Issue by pdxjohnny** [tpm2-software/tpm2-pytss#46]
- [ ] `memset()`
- [ ] `sizeof()` for each type

**Comment by williamcroberts** [comment]
Doesn't ctypes have this?

**Comment by williamcroberts** [comment]
for sizeof we can have our structures extend ctypes.Structure and then ctypes.sizeof should work. Is their a benefit to rolling our own? ctypes is part of the standard lib for python right?

**Comment by williamcroberts** [comment]
@pdxjohnny what was your thoughts behind this? Do we still need it?

**Comment by williamcroberts** [comment]
I don't think we need this, closing.
