### ISSUE TITLE
Convert TPMT_SIGNATURE to DER

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-pytss#463]
I tried do verify a signature, returned by  `esys.get_time` , with `fapi.verify_signature`.
`fapi.verify_signature` expects a DER signature. The tpm2 tool command `tpm2_gettime` has
the option `--format=plain` for this purpose.
Is there a way to convert a TPMT_SIGNATURE to DER with tpm2_pytss?
`

**Comment by whooo** [comment]
There is no public method for that, you can have a look at https://github.com/tpm2-software/tpm2-pytss/blob/1465ae2f2bf2753b4d9dccd71d66f2088cde263d/src/tpm2_pytss/internal/crypto.py#L430 to see how we handle signature verification using the cryptography module for ECDSA signatures.

Adding the `__bytes__` method to TPMT_SIGNATURE which would return the underlying bytes for RSA and HMAC signatures and the DER encoding for ECSA signatures could be useful, would that work for `fapi.verify_signaure`?

**Comment by JuergenReppSIT** [comment]
> Adding the `__bytes__` method to TPMT_SIGNATURE which would return the underlying bytes for RSA and HMAC signatures and the DER encoding for ECSA signatures could be useful, would that work for `fapi.verify_signaure`?

Yes, that would be great. Currently I did the verification using tss2_verifysignature with the  DER output from tpm2_gettime and it worked. With tpm2_pytss the implementation seemed to be easier because of good features to access data in the binary blobs.
