### ISSUE TITLE
tpm2-pytss install suddenly not working (Ubuntu 20.04, WSL2)

### ISSUE THREAD

**Issue by Jarkre** [tpm2-software/tpm2-pytss#465]
I tried to install tpm2_pytss to Ubuntu 20.04 but the following error message is shown:

    cffi.CDefError: cannot parse "#if !defined(DISABLE_VENDOR)"
    <cdef source string>:2193:2: before: if

What could be the reason for this?

The full log:

pip install tpm2_pytss --no-cache-dir

Collecting tpm2_pytss
  Downloading tpm2-pytss-1.2.0.tar.gz (178 kB)
     |████████████████████████████████| 178 kB 5.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpxo948zq3 prepare_metadata_for_build_wheel /tmp/tmpgjlmslw0
         cwd: /tmp/pip-install-nqwdlqvq/tpm2-pytss
    Complete output (66 lines):
    adding path: /tmp/pip-install-nqwdlqvq/tpm2-pytss/scripts
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/cffi/cparser.py", line 336, in _parse
        ast = _get_parser().parse(fullcsource)
      File "/usr/local/lib/python3.8/dist-packages/pycparser/c_parser.py", line 147, in parse
        return self.cparser.parse(
      File "/usr/local/lib/python3.8/dist-packages/pycparser/ply/yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "/usr/local/lib/python3.8/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "/usr/local/lib/python3.8/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "/usr/local/lib/python3.8/dist-packages/pycparser/c_parser.py", line 1931, in p_error
        self._parse_error(
      File "/usr/local/lib/python3.8/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: <cdef source string>:2193:2: before: if
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/tmpxo948zq3", line 280, in <module>
        main()
      File "/tmp/tmpxo948zq3", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpxo948zq3", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 237, in <module>
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
        _Distribution.__init__(
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-j6d8w05f/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.8/dist-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python3.8/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python3.8/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "scripts/libtss2_build.py", line 70, in <module>
        ffibuilder.cdef(open("libesys.h").read())
      File "/usr/local/lib/python3.8/dist-packages/cffi/api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "/usr/local/lib/python3.8/dist-packages/cffi/api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "/usr/local/lib/python3.8/dist-packages/cffi/cparser.py", line 389, in parse
        self._internal_parse(csource)
      File "/usr/local/lib/python3.8/dist-packages/cffi/cparser.py", line 394, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "/usr/local/lib/python3.8/dist-packages/cffi/cparser.py", line 338, in _parse
        self.convert_pycparser_error(e, csource)
      File "/usr/local/lib/python3.8/dist-packages/cffi/cparser.py", line 367, in convert_pycparser_error
        raise CDefError(msg)
    cffi.CDefError: cannot parse "#if !defined(DISABLE_VENDOR)"
    <cdef source string>:2193:2: before: if
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpxo948zq3 prepare_metadata_for_build_wheel /tmp/tmpgjlmslw0 Check the logs for full command output.

**Comment by whooo** [comment]
Which version of tpm2-tss are you building against?

**Comment by Jarkre** [comment]
Thank you, that solved the problem. I tried with earlier version of tpm2-tss and then tpm2-pytss build was successful.

The error log above was shown with this combination:
tpm2-tss:   15.11.2022   34bf7bff93793ae9d91069bf1fb58b41832f5e73
tpm2-pytss:  17.11.2022 1465ae2f2bf2753b4d9dccd71d66f2088cde263d

but after changing to this, the tpm2-pytss building was ok:
tpm2-tss:   2.11.2022   21a8b31d4f959bfcee0e78d3d98b1492abf499e3
tpm2-pytss:  17.11.2022 1465ae2f2bf2753b4d9dccd71d66f2088cde263d

**Comment by williamcroberts** [comment]
Sorry folks, I bumped into this too and never sent my PR, thanks @whooo

**Comment by Jarkre** [comment]
Tried with latest tpm2-tss master and tpm2-pytss master. Works ok. Also, tpm2-pkcs11-tools install works ok. 
Thank you again.

tpm2-pytss istall:

python3 -m pip install git+https://github.com/tpm2-software/tpm2-pytss.git
Collecting git+https://github.com/tpm2-software/tpm2-pytss.git
  Cloning https://github.com/tpm2-software/tpm2-pytss.git to /tmp/pip-req-build-65bswics
  Running command git clone -q https://github.com/tpm2-software/tpm2-pytss.git /tmp/pip-req-build-65bswics
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cryptography>=3.0 in /usr/local/lib/python3.8/dist-packages (from tpm2-pytss==1.2.1.dev73+gbba1485) (38.0.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/dist-packages (from tpm2-pytss==1.2.1.dev73+gbba1485) (6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tpm2-pytss==1.2.1.dev73+gbba1485) (21.3)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from tpm2-pytss==1.2.1.dev73+gbba1485) (1.15.1)
Requirement already satisfied: asn1crypto in /usr/local/lib/python3.8/dist-packages (from tpm2-pytss==1.2.1.dev73+gbba1485) (1.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->tpm2-pytss==1.2.1.dev73+gbba1485) (3.0.9)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.0.0->tpm2-pytss==1.2.1.dev73+gbba1485) (2.21)
Building wheels for collected packages: tpm2-pytss
  Building wheel for tpm2-pytss (PEP 517) ... done
  Created wheel for tpm2-pytss: filename=tpm2_pytss-1.2.1.dev73+gbba1485-cp38-cp38-linux_x86_64.whl size=887099 sha256=d9e63eb0365e784eb93d580217e7706901a3dea81cce50981b5bba6a0e36fa11
  Stored in directory: /tmp/pip-ephem-wheel-cache-gucckv5b/wheels/a5/37/19/2071294f499fbbea98dc4c95e28caac93e105cb48982befd34
Successfully built tpm2-pytss
Installing collected packages: tpm2-pytss
  Attempting uninstall: tpm2-pytss
    Found existing installation: tpm2-pytss 1.2.0
    Uninstalling tpm2-pytss-1.2.0:
      Successfully uninstalled tpm2-pytss-1.2.0
Successfully installed tpm2-pytss-1.2.1.dev73+gbba1485

--------------------------------------------------------------------------------------------------------------------------------
tpm2-pkcs11-tools install:

cd tpm2_pkcs11/tools
pip install .
Processing /tpm_simulator/tpm2-pkcs11/tools
Requirement already satisfied: bcrypt in /usr/local/lib/python3.8/dist-packages (from tpm2-pkcs11-tools==1.33.7) (4.0.1)
Requirement already satisfied: cryptography>=3.0 in /usr/local/lib/python3.8/dist-packages (from tpm2-pkcs11-tools==1.33.7) (38.0.3)
Requirement already satisfied: pyasn1 in /usr/local/lib/python3.8/dist-packages (from tpm2-pkcs11-tools==1.33.7) (0.4.8)
Requirement already satisfied: pyasn1_modules in /usr/local/lib/python3.8/dist-packages (from tpm2-pkcs11-tools==1.33.7) (0.2.8)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/dist-packages (from tpm2-pkcs11-tools==1.33.7) (6.0)
Requirement already satisfied: tpm2_pytss in /usr/local/lib/python3.8/dist-packages (from tpm2-pkcs11-tools==1.33.7) (1.2.1.dev73+gbba1485)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.0->tpm2-pkcs11-tools==1.33.7) (1.15.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tpm2_pytss->tpm2-pkcs11-tools==1.33.7) (21.3)
Requirement already satisfied: asn1crypto in /usr/local/lib/python3.8/dist-packages (from tpm2_pytss->tpm2-pkcs11-tools==1.33.7) (1.5.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.0->tpm2-pkcs11-tools==1.33.7) (2.21)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->tpm2_pytss->tpm2-pkcs11-tools==1.33.7) (3.0.9)
Building wheels for collected packages: tpm2-pkcs11-tools
  Building wheel for tpm2-pkcs11-tools (setup.py) ... done
  Created wheel for tpm2-pkcs11-tools: filename=tpm2_pkcs11_tools-1.33.7-py3-none-any.whl size=37168 sha256=e977553061303fd3fa0aab4ebb261ee4c92e86a5c16855ffd4f89019db51893e
  Stored in directory: /tmp/pip-ephem-wheel-cache-jxilspr7/wheels/12/72/0c/f4302342131891d5c13690d09ec8204750f56b787c84be9c23
Successfully built tpm2-pkcs11-tools
Installing collected packages: tpm2-pkcs11-tools
  Attempting uninstall: tpm2-pkcs11-tools
    Found existing installation: tpm2-pkcs11-tools 1.33.7
    Uninstalling tpm2-pkcs11-tools-1.33.7:
      Successfully uninstalled tpm2-pkcs11-tools-1.33.7
Successfully installed tpm2-pkcs11-tools-1.33.7
root@a0bf0000d889:/tpm_simulator/tpm2-pkcs11/tools#
----------------------------------------------------------------------------------------------------------------
tpm2-tss 

git status
On branch master
Your branch is up to date with 'origin/master'.

git log
commit c17e3989bf2fd83bdac68e79b3b5a0e20fbb2a99 (HEAD -> master, origin/master, origin/HEAD)
Author: malikabhi05 <abhishek.malik@intel.com>
Date:   Sat Nov 19 19:35:07 2022 -0800

    esys_iutil.c: Adding range for ACs
    
    Signed-off-by: malikabhi05 <abhishek.malik@intel.com>
    Signed-off-by: William Roberts <william.c.roberts@intel.com>

**Comment by williamcroberts** [comment]
Closed since fixed
