### ISSUE TITLE
FAPI Documentation

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-pytss#466]
The documentation of the FAPI API can be produced with `./scripts/docs.sh `
On https://tpm2-pytss.readthedocs.io/en/latest/fapi.html there is no documentation of the FAPI functions.
Is there a reason for that?

**Comment by whooo** [comment]
I wonder if it's due to library version checks we have for FAPI (and other parts), so for local doc generation sphinx can import the module but for automatic doc generation FAPI won't be imported.
