### ISSUE TITLE
Calling fapi_Sign() method with proper arguments (digest)

### ISSUE THREAD

**Issue by PrzemyslawSamsel** [tpm2-software/tpm2-pytss#47]
Hi, this would be actually very simple. I have this function from fapi: 
```python
Sign(keyPath: char const *, padding: char const *, digest: uint8_t const *, digestSize: size_t, signature: uint8_t **, signatureSize: size_t *, publicKey: char **, certificate: char **) → TSS2_RC
```
And I am trying to pass arguments to it, specifically the 3rd one (digest):

```python
fapi_ctx.Sign(path_to_key, None, ???, digest_size, sig_holder, None, None, None)
```
After several hours of trial and error, trying everything from struct.pack(), through ctypes, to simply using several methods and fields in your class tpm2_pytss.binding (using dir()) I still receive this error: 

```python
Traceback (most recent call last):
  File "lab5.py", line 84, in <module>
    sign(ctx, stck, "HS/lab5_key", "qwe123", doc_txt)
  File "lab5.py", line 77, in sign
    fapi_ctx.Sign(path_to_key, None, digest_pointer, 32, sig_holder, None, None, None)
  File "/media/sf_LNX_FILES/SEM2/ZIO/tpm2-pytss/tpm2_pytss/context.py", line 78, in wrapper
    return custom_wrap(func)(self.ctxp, *args, **kwds)
  File "/media/sf_LNX_FILES/SEM2/ZIO/tpm2-pytss/tpm2_pytss/context.py", line 112, in wrapper
    result = func(self, *args, **kwds)
  File "/media/sf_LNX_FILES/SEM2/ZIO/tpm2-pytss/tpm2_pytss/util/swig.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/media/sf_LNX_FILES/SEM2/ZIO/tpm2-pytss/tpm2_pytss/exceptions.py", line 48, in wrapper
    rc = func(*args, **kwargs)
  File "/media/sf_LNX_FILES/SEM2/ZIO/tpm2-pytss/tpm2_pytss/fapi_binding.py", line 14997, in Fapi_Sign
    return _fapi_binding.Fapi_Sign(context, keyPath, padding, digest, digestSize, signature, signatureSize, publicKey, certificate)
TypeError: in method 'Fapi_Sign', argument 4 of type 'uint8_t const *'
```

I am not asking for help here, although it would be highly appreciated - instead I would just like to inform you that there is such a case, in which documentation to pytss doesn't help and hours of surfing web does no either. Perhaps there is a room for some improvement that would make passing parameters a little bit simpler for beginners?

**Comment by PrzemyslawSamsel** [comment]
Just to clarify the example, argument I used for digest was in my case: 

```python
    shaobj = hashlib.sha256()
    shaobj.update(document.encode())
    
    digest_pointer = ctypes.cast(shaobj.digest(), ctypes.POINTER(ctypes.c_uint8 * shaobj.digest_size))
    digest_size = shaobj.digest_size
```

**Comment by joholl** [comment]
Relevant: https://stackoverflow.com/questions/64839609/pytss-passing-arguments-to-fapi-sign-method-invalid-argument-type-fapi-sig

I think this is related to #36

**Comment by PrzemyslawSamsel** [comment]
Yes, I just wanted to add that myself. As everything is explained there, I think we may close this issue. Thanks again for the help
