### ISSUE TITLE
{AttributeError}'TPMT_PUBLIC' object has no attribute '_cdata'

### ISSUE THREAD

**Issue by jwz104** [tpm2-software/tpm2-pytss#480]
I have an issue when I convert a public key to a `TPM2B_PUBLIC`. The following code fails (sometimes):
```python
# tpm_cert is a cryptography certificate instance of an ECC EK certificate.
endorsement_key = TPM2B_PUBLIC.from_pem(
    tpm_cert.public_bytes(encoding=serialization.Encoding.DER),
    symmetric="aes128cfb", 
)
```

I get the following exception:
```
  File "/usr/local/lib/python3.9/site-packages/tpm2_pytss/types.py", line 1195, in from_pem
    pa = TPMT_PUBLIC.from_pem(
  File "/usr/local/lib/python3.9/site-packages/tpm2_pytss/types.py", line 976, in from_pem
    _public_from_encoding(data, p, password=password)
  File "/usr/local/lib/python3.9/site-packages/tpm2_pytss/internal/crypto.py", line 154, in _public_from_encoding
    obj.type = TPM2_ALG.ECC
  File "/usr/local/lib/python3.9/site-packages/tpm2_pytss/types.py", line 140, in __setattr__
    _cdata = object.__getattribute__(self, "_cdata")
AttributeError: 'TPMT_PUBLIC' object has no attribute '_cdata'
```

The exception occurs when I call any field (e.g. `type`) on the `TPMT_PUBLIC` instance. See the debugger below:
![afbeelding](https://user-images.githubusercontent.com/6162114/205036180-500f88af-396b-4072-abc8-de731ffe70b1.png)

My setup might be a bit weird:
- I run on Mac OS 12.6
- I using a remote Python interpreter from a Docker container so I have TPM2-TSS.
- I'm using Python 3.9
- Using version 2.4.0 of tpm2-pytss

The weird thing is that I sometimes do not get the exception. Does anyone know how I can fix this?

**Comment by jwz104** [comment]
![afbeelding](https://user-images.githubusercontent.com/6162114/205053397-4676bfd1-2688-445b-a07f-a57ccafbcd2c.png)

Looks like I found the place where to error comes from, will look into a way to fix it :)

https://github.com/tpm2-software/tpm2-pytss/blob/51823ef355fdf2cf2320467fa29bcd18ddc9a8b1/src/tpm2_pytss/types.py#L80

---

Forgot to mention that I only have this issue while testing.

**Comment by jwz104** [comment]
For anyone else with this issue when unittesting a project with `tpm2_pytss` as test dependency, adding this patch will fix the issue:
```python
@patch('tpm2_pytss.internal.utils.__MOCK__', False)
def test_tpm_stuff(self):
    # Test stuff
```
---
This is a hack, not a real solution. Will close this issue because I can life with this fix in my project :)

**Comment by williamcroberts** [comment]
> For anyone else with this issue when unittesting a project with `tpm2_pytss` as test dependency, adding this patch will fix the issue:
> 
> ```python
> @patch('tpm2_pytss.internal.utils.__MOCK__', False)
> def test_tpm_stuff(self):
>     # Test stuff
> ```
> 
> This is a hack, not a real solution. Will close this issue because I can life with this fix in my project :)

Ahh you're using mock in your unit testing which causes our __MOCK__ to be true. We really only need this for
building docs, so perhaps we can use an env variable or something better. I'm going to reopen this so we fix it.

**Comment by jwz104** [comment]
When is a version containing #481 being release? I found out that my workaround doesn't always work because patching will call all `__init__.py` files of pytss, causing the default function arguments in `ESAPI.py` to be initialized without the patch being applied.

**Comment by williamcroberts** [comment]
> When is a version containing #481 being release? I found out that my workaround doesn't always work because patching will call the `__init__.py`, causing the default function arguments in `ESAPI.py` to be initialized without the patch being applied.
> 
> https://github.com/tpm2-software/tpm2-pytss/blob/d494b9cf1d555672150bc8effb21a6c37676f7de/src/tpm2_pytss/__init__.py#L2

2.1.0-rc0 is in process now, will post an email to the list when it is published on pypi
