### ISSUE TITLE
checking for module tpm2-pytss in python ...configure:error: not found

### ISSUE THREAD

**Issue by sanketFT** [tpm2-software/tpm2-pytss#483]
Hi Everyone,

I am trying do ./configure and I am getting the error as  checking for module tpm2-pytss in python ...configure:error: not found
But the tpm2-pytss is already installed when I tried to reinstall it says Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.9/dist-packages (from packaging->tpm2_pytss) (3.0.9)

Looking for some help.

Thanks and regards,
Sanket

**Comment by whooo** [comment]
tpm2-pytss doesn't use autoconf, so we don't have a configure scripts, so I suspect the issue is within another project.

**Comment by sanketFT** [comment]
another project means example

**Comment by whooo** [comment]
another project as is not tpm2-pytss

**Comment by sanketFT** [comment]
K thanks will look into it

**Comment by williamcroberts** [comment]
Please open the ticket to the right project when you figure it out :-p
