### ISSUE TITLE
Make ecdh_zgen output match Cryptography ECDH exchange

### ISSUE THREAD

**Issue by jwz104** [tpm2-software/tpm2-pytss#488]
I would like to use the `ecdh_zgen` command to recover a shared secret that should match the `ecdh` exchange from the [Python Cryptography](https://cryptography.io/en/latest/) library.

This is what I have so far:
```python
with ESAPI() as api:
    # Generate a key with the TPM.
    primary_handle, _, _, _, _ = api.create_primary(TPM2B_SENSITIVE_CREATE(), "ecc")
    tpm_private, tpm_public, _, _, _ = api.create(primary_handle, None, in_public="ecc256")
    handle = api.load(primary_handle, tpm_private, tpm_public)

    # Generate another key using cryptography.
    key = ec.generate_private_key(ec.SECP256R1())

    # Create secret using the cryptography private key.
    public_key = public_to_key(tpm_public.publicArea)
    secret = key.exchange(ec.ECDH(), public_key)  # 32 byte length.

    # Create secret using the TPM private key.
    x = key.public_key().public_numbers().x
    y = key.public_key().public_numbers().y
    in_point = TPM2B_ECC_POINT(
        TPMS_ECC_POINT(
            # Not sure if this is the correct way to convert x and y to bytes.
            x=x.to_bytes(length=32, byteorder="big", signed=False),
            y=y.to_bytes(length=32, byteorder="big", signed=False),
        )
    )

    out_point = api.ecdh_zgen(handle, in_point)
    x = int.from_bytes(out_point.point.x, 'big', signed=False)
    y = int.from_bytes(out_point.point.y, 'big', signed=False)

    # What do I have to do with x and y (or out_point) to get the shared secret that matches `secret`?
```
---

The docs describe the following:
> Recovers the shared secret value (Z) from a public point and a specified private key. It will perform the multiplication of the provided inPoint (QB) with the private key (ds) and return the coordinates of the resultant point (Z = (xZ , yZ) ≔ [hds]QB; where h is the cofactor of the curve)

I only still don't understand how I can get Z, instead of x and y. So therefor my question: How can I receive the shared ECDH secret in bytes using an EC key generated by the TPM?

**Comment by jwz104** [comment]
Well that was solved quickly. It turned out that `bytes(out_point.point.x) == secret`.

Sorry for bothering.

**Comment by williamcroberts** [comment]
> Well that was solved quickly. It turned out that `bytes(out_point.point.x) == secret`.
> 
> Sorry for bothering.

I had this same issue once, I was like where is "Z", oh by convention it's the output's "X" point....
