### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ashburry-chat-irc** [tpm2-software/tpm2-pytss#491]
```
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-c8xboqc5\overlay\Lib\site-packages\setuptools_scm\version.py", line 203, in _parse_tag
          assert version is not None
      AssertionError
      [end of output]
```
I am trying to install on Windows 10 via `py -3.10 -m pip install git+https://salsa.debian.org/cmhe/tpm2-pytss.git`

**Comment by williamcroberts** [comment]
I get the same error on Linux, note that's not my repo, that's something else. Any reason you don't install a stable version from PyPi?

```bash
python3 -m pip install tpm2-pytss
```

**Comment by whooo** [comment]
Closing as it's related to another repo.
