### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pierre03** [tpm2-software/tpm2-pytss#503]
Hello,
I have an install error when i use pip V22 to install the module, my python version is 3.10.
Can you tell me which is the compatible version for Python, please?

**Comment by whooo** [comment]
All currently maintained python releases (3.7 - 3.11 as of now) are supported.

**Comment by whooo** [comment]
Do you still have issues or where you able to solve them?

**Comment by whooo** [comment]
Closing for now due to no answer to the questions, reopen if you want.
