### ISSUE TITLE
FAPI: Setting up a sealed object, protected via pcr policy, and accessed over an encrypted session

### ISSUE THREAD

**Issue by terilenard** [tpm2-software/tpm2-pytss#504]
Hello,

I am trying to achieve the following thing in python and in tpm2-tools, but hit the same wall. 
Related issue from tpm2-tools [3227](https://github.com/tpm2-software/tpm2-tools/issues/3227).

The ultimate goal is to seal a secret which can be accessed only when a pcr policy is met. Additionally, I want to have a authenticated and encrypted communication between the tpm and the FAPI application.

Please find below the fapi-profile and python code.

FAPI-profile:
```
{
    "type": "TPM2_ALG_ECC",
    "nameAlg":"TPM2_ALG_SHA256",
    "srk_template": "system,restricted,decrypt,0x81000001",
    "srk_description": "Storage root key SRK",
    "srk_persistent": 0,
    "ek_template":  "system,restricted,decrypt",
    "ek_description": "Endorsement key EK",
    "ecc_signing_scheme": {
        "scheme":"TPM2_ALG_ECDSA",
        "details":{
            "hashAlg":"TPM2_ALG_SHA256"
        },
    },
    "sym_mode":"TPM2_ALG_CFB",
    "sym_parameters": {
        "algorithm":"TPM2_ALG_AES",
        "keyBits":"128",
        "mode":"TPM2_ALG_CFB"
    },
    "session_hash_alg": "TPM2_ALG_SHA256",
    "session_symmetric":{
        "algorithm":"TPM2_ALG_AES",
        "keyBits":"128",
        "mode":"TPM2_ALG_CFB"
    },
    "sym_block_size": 16,
    "pcr_selection": [
       { "hash": "TPM2_ALG_SHA1",
         "pcrSelect": [ ],
       },
       {
         "hash": "TPM2_ALG_SHA256",
         "pcrSelect": [ 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
       }
    ],
    "curveID": "TPM2_ECC_NIST_P256",
    "ek_policy": {
        "description": "Endorsement hierarchy used for policy secret.",
        "policy":[
            {
                "type":"POLICYSECRET",
                "objectName": "4000000b",
            }
        ]
    }
}
```

The profile doesn't have anything uncommon, what interests me if the usage of:
```
"session_hash_alg": "TPM2_ALG_SHA256",
    "session_symmetric":{
        "algorithm":"TPM2_ALG_AES",
        "keyBits":"128",
        "mode":"TPM2_ALG_CFB"
    }
```
is correct?

Even with this in the profile, the secret is visible on the communication between the FAPI app and the virtual TPM (with tpm2-abrmd).

Source code:
```
import sys

sys.path.append(".") # This is executed from the tests dir 

from tpm2_pytss import *
from TSS2_BaseTest import TpmSimulator

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend

def sha256(data: bytes) -> bytes:
    """Calculate the SHA256 digest of given data."""
    digest = hashes.Hash(hashes.SHA1(), backend=default_backend())
    digest.update(data)
    digest = digest.finalize()
    return digest

tpm = TpmSimulator.getSimulator()
tpm.start()

fapi_config = FAPIConfig(
        temp_dirs=True,
        tcti=tpm.tcti_name_conf,
        ek_cert_less="yes",
        profile_name="P_ECCP256SHA256",
        profile_dir=".",
        firmware_log_file="/dev/null",
        ima_log_file="/dev/null",
    )

fapi_ctx = FAPI()
fapi_ctx.provision()

profile_name = fapi_ctx.config.profile_name
path = f"/{profile_name}/HS/SRK/seal_obj"
seal_data = "secret".encode()

pcr_policy="""{
    "description":"Policy PCR 0 TPM2_ALG_SHA1",
    "policy":[
        {
            "type":"POLICYPCR",
            "pcrs":[
                {
                    "pcr":0,
                    "hashAlg":"TPM2_ALG_SHA1",
                    "digest":"0000000000000000000000000000000000000000"
                }
            ]
        }
    ]
}

"""
fapi_ctx.import_object(path="/policy/pcr-policy", import_data=pcr_policy)
success = fapi_ctx.create_seal(path=path, data=seal_data,
                      policy_path="/policy/pcr-policy")

print(success)

# pcr_data = b"abc"
# pcr_digest = sha256(pcr_data)
# fapi_ctx.pcr_extend(index=0,data=pcr_digest)
unsealed_data = fapi_ctx.unseal(path=path)

print(unsealed_data)


fapi_ctx.delete("/")
fapi_ctx.close()
fapi_config.close()
tpm.close()
```

Thank you!
Teri

**Comment by whooo** [comment]
I'm not to familiar with FAPI, but have you tried without ek_cert_less="yes" against a real TPM? I might be wrong, but IIRC the basis for default parameter encryption is based around the EK.
How do you check the traffic between the application and the simulator?

**Comment by terilenard** [comment]
Hi @whoo,

At the moment I do not have a real tpm, but will have one in the following week.
As for the traffic, with wireshark.

If the issue could be around EK, I will play a little with it and the virtual tpm, to see what comes out.

Teri

**Comment by JuergenReppSIT** [comment]
Hi @terilenard ,
there are several cases were FAPI does not encrypt the parameters. We already have a PR:
https://github.com/tpm2-software/tpm2-tss/pull/2569
Unfortunately we currently have a problem because none of the other maintainers finds time to approve the PRs.
I have created a private branch where most of the bugs in the PR congestion are fixed. You could use this branch:
```
git clone https://github.com/JuergenReppSIT/tpm2-tss.git
cd tpm2-tss
git checkout priv
./bootstrap
./configure
make -j 
sudo make install
``` 
Sorry for inconvenience. I hope we can create a new bugfix release in the near future.

**Comment by whooo** [comment]
> EDIT 2: The reason why I picked FAPI is because I couldn't find in the source code and test of ESAPI how can I create a sealed object with a PCR policy.
> 

If you are running tpm2-tss version 4.0.0 or later and you have built tpm2-pytss against that release you can use the policy module, it's not that well documented but there are some unit tests and then use that together with ESAPI.
Other then that you can call the methods in ESAPI to seal/unseal and setup the policy (see create_primary, create, startauthsession, unseal and policy_pcr in the ESAPI class).
But FAPI with @JuergenReppSIT fixes will be much easier.

**Comment by terilenard** [comment]
@JuergenReppSIT @whooo Thank you very much guys! Will have a look over the suggestions and come back with some feedback.

Teri.

**Comment by terilenard** [comment]
Update 1: By reinstalling the branch from https://github.com/tpm2-software/tpm2-tss/pull/2569 over my existing installation, FAPI now seems to work. The "secret" is not visible in the packets exchanged between the FAPI script and the virtual TPM. 

Update 2: I tried to reinstall the mentioned branch on a clean system which succeeded, of course. Afterwards, when trying to install tpm2-tools or pytss, there was a conflict of versioning, tpm2-tools and pytss expected a newer version of tpm2-tss to be present. Of course, this is just a side effect from my perspective, which should not be a problem when the PR is accepted in tpm2-tss.

For the moment, I will continue working with FAPI, and probably will do some testing with ESAPI too. From my perspective, issue can be closed since there is a fix pending on tpm2-tss.

**Comment by whooo** [comment]
I'll close this issue for now, good luck with your project :-)
