### ISSUE TITLE
FAPI: using create_key() to create an attestation key 

### ISSUE THREAD

**Issue by terilenard** [tpm2-software/tpm2-pytss#505]
In the standard [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf), the following is mentioned:

_An AK MUST have the following characteristics:
• Restricted
• Signing
• Not-decrypting
• FixedTPM_

But, while trying to execute something similar to the code bellow:
```
self._ctx.create_key(path=self._aik_path_tss, type_=self._aik_attributes)
```

where `self._ctx` is an instance of `FAPI()`,  `self._aik_path_tss` is `/P_ECCP256SHA256/HS/SRK/key_aik` and `self._aik_attributes` has value of `"sign, restricted, fixedTPM, 0x81000007"`. I omitted the `decrypt` key attribute to get the `Not-decrypting` attribute, if this is correct. At last, the following error occurs:

```
ERROR:fapi:src/tss2-fapi/ifapi_helpers.c:96:ifapi_set_key_flags() ErrorCode (0x0006000b) Invalid flag: fixedTPM 
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:194:Fapi_CreateKey_Async() Set key flags for key ErrorCode (0x0006000b) 
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:99:Fapi_CreateKey() ErrorCode (0x0006000b) Key_Create 
Traceback (most recent call last):
  File "tpm_controller.py", line 105, in <module>
    controller._create_aik()
  File "tpm_controller.py", line 34, in _create_aik
    success = self._ctx.create_key(path=self._aik_path_tss, type_=self._aik_attributes)
  File "/usr/local/lib/python3.6/dist-packages/tpm2_pytss/FAPI.py", line 414, in create_key
    ret, acceptable=lib.TSS2_FAPI_RC_PATH_ALREADY_EXISTS if exists_ok else None
  File "/usr/local/lib/python3.6/dist-packages/tpm2_pytss/internal/utils.py", line 176, in _chkrc
    raise TSS2_Exception(rc)
tpm2_pytss.TSS2_Exception.TSS2_Exception: fapi:A parameter has a bad value
```

In the code above `tpm_controller.py` contains a class that uses FAPI to interact with the TPM.

Without the property `fixedTPM` everything is fine. Is there a correct way of creating an attestation key in FAPI? I am aware that there is support for it in tpm2-tools and tpm2-pytss esys. 

If the above method of working with an attestation key it is not correct, is it more appropriate to generate the ak with tpm2_createak? But then how should I load the ak into FAPI?

Thank you,
Teri.

**Comment by JuergenReppSIT** [comment]
FixedTPM can't be passed as a flag but should be set automatically if the key is not exportable. If the tpm tools are installed you can check the attributes:
`tss2_gettpm2object -p /P_ECCP256SHA256/HS/SRK/key_aik -c /tmp/test.ctx`
`tpm2_readpublic -c /tmp/test.ctx`

**Comment by terilenard** [comment]
Executing `tss2_gettpm2object -p P_ECCP256SHA256/HS/SRK/key_aik -c /tmp/test.ctx` generated an error for some reason:

```
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:534:rel_path_to_abs_path() ErrorCode (0x00060020) Key P_ECCP256SHA256/HS/SRK/key_aik not found. 
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:582:ifapi_keystore_load_async() ErrorCode (0x00060020) Object P_ECCP256SHA256/HS/SRK/key_aik not found. 
ERROR:fapi:src/tss2-fapi/api/Fapi_GetEsysBlob.c:259:Fapi_GetEsysBlob_Finish() ErrorCode (0x00060020) Could not open: P_ECCP256SHA256/HS/SRK/key_aik 
ERROR:fapi:src/tss2-fapi/api/Fapi_GetEsysBlob.c:101:Fapi_GetEsysBlob() ErrorCode (0x00060020) Entity_GetEsysBlob 
Fapi_GetAppData(0x60020) - fapi:The key was not found
```

But, by reading the public part of the handle with `tpm2_readpublic`, the output looks good:

```
name: 000b5cdcf1ac5d1e865eb5adaf93f34558fb07568e3b88694fb84d4b0185f14fbc41
qualified name: 000be5d3380e1b810e6ac138ad68896d334f9cbf772813672e855c5daa6e87f49176
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign
  raw: 0x50072
type:
  value: ecc
  raw: 0x23
curve-id:
  value: NIST p256
  raw: 0x3
kdfa-alg:
  value: null
  raw: 0x10
kdfa-halg:
  value: (null)
  raw: 0x0
scheme:
  value: ecdsa
  raw: 0x18
scheme-halg:
  value: sha256
  raw: 0xb
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
x: 801beb2489bc7bf2b7ffddd2446755277ca45c7c99dcdef89ed51475db0c9e48
y: f6c897c6ccbb60ea9bcc9c63f6f7249165a2b8868b3154da270aaf58e86fabf9
```

If there is nothing wrong with the output, the issue can be closed.

Thank you for the help so fast!

**Comment by JuergenReppSIT** [comment]
@terilenard One question: How can you use tpm2_readpublic if  P_ECCP256SHA256/HS/SRK/key_aik  does not exist?

**Comment by terilenard** [comment]
If it is helpfull, I tried to use that key to quote and verify. While calling 

```
self._ctx.quote(path=self._aik_path_tss, pcrs=[7, 9])
```

with `self._aik_path_tss` being `/P_ECCP256SHA256/HS/SRK/key_aik`, the following error occurs:

```
WARNING:esys:src/tss2-esys/api/Esys_FlushContext.c:234:Esys_FlushContext_Finish() Received TPM Error 
ERROR:fapi:src/tss2-fapi/api/Fapi_Quote.c:404:Fapi_Quote_Finish() Error: Sign ErrorCode (0x000001c4) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Quote.c:134:Fapi_Quote() ErrorCode (0x000001c4) PCR_Quote 
Traceback (most recent call last):
  File "tpm_controller.py", line 113, in <module>
    info, signature, pcr_log, certificate = controller.quote()
  File "tpm_controller.py", line 45, in quote
    return self._ctx.quote(path="HS/SRK/key_aik", pcrs=[7, 9])
  File "/usr/local/lib/python3.6/dist-packages/tpm2_pytss/FAPI.py", line 1055, in quote
    _chkrc(ret)
  File "/usr/local/lib/python3.6/dist-packages/tpm2_pytss/internal/utils.py", line 176, in _chkrc
    raise TSS2_Exception(rc)
tpm2_pytss.TSS2_Exception.TSS2_Exception: tpm:parameter(1):value is out of range or is not correct for the context
```

Let me know if this is anyway helpful. Initially I didn't added this context to the problem since I tried to figure out why doesn't work.

**Comment by JuergenReppSIT** [comment]
That's really strange. The type of the handle for TM2_Quote is TPMI_DH_OBJECT. The TPMI_DH_OBJECT interface type is a handle that references a loaded object. The handles in this set are used to refer to either transient or persistent object. 
I have tested quote with a persistent handle 0x81000005 with:
- ibm tpm simulator
- amd firmware tpm
- infineon tpm

`tpm2_readpublic -c 0x81000005` seemed to be ok but in all cases 0x1c4 was returned for the quote command. The testś worked if no persistent handle was used.
@AndreasFuchsTPM Do you have an explanation for this behaviour?

**Comment by JuergenReppSIT** [comment]
@terilenard @AndreasFuchsTPM Sorry I was blind.
It's an error in Fapi_Quote which tries to flush a persistent object. I will create a PR.

**Comment by terilenard** [comment]
Thank you for your input and help @JuergenReppSIT . Will let you know if I find more things 😄 .

**Comment by JuergenReppSIT** [comment]
@terilrand I have create #2594 to fix this problem.

**Comment by terilenard** [comment]
> @terilrand I have created [tpm2-software/tpm2-tss#2594](https://github.com/tpm2-software/tpm2-tss/pull/2594) to fix this problem.

I have recompile tpm2-tss with your changes from #2594. I do not get the exception anymore.

**Comment by terilenard** [comment]
The fix was merged to master. I think the issue can be closed.

**Comment by whooo** [comment]
closing as the fix for tpm2-tss has been merged
