### ISSUE TITLE
Tests test_exec_sign_callback and test_exec_polauth_callback in test_policy.py use prime192v1 key not supported in Fedora

### ISSUE THREAD

**Issue by Jakuje** [tpm2-software/tpm2-pytss#527]
I am updating the package in Fedora and we have tree tests failing because OpenSSL in Fedora (and and RHEL based system) is for legal reasons missing some curves, namely mostly brainpool, but also the prime192v1 but also sect163r2. This makes the following tests failing:

 * `test_crypto.py`: `test_ecc_bad_curves`: Fails with message `Unsupported key format` instead of `unsupported curve: sect163r2` (I have this patched since [last version](https://src.fedoraproject.org/rpms/python-tpm2-pytss/blob/rawhide/f/python-tpm2-pytss-1.2.0-openssl.patch).
 * `test_policy.py`: `test_exec_polauth_callback` and `test_exec_sign_callback` (using the same key): Our OpenSSL fails to import the prime192v1 private key. The workaround could be to use different curve/key to make it more. So far I will skip this test downstream too, but it would be good to have an upstream and compatible solution that will work everywhere

It also fails to build on 32b arch, but I do not think this is a problem for anyone in 2023.

On s390x it fails waiting for the TPM2 in this test:
```
________________________ TestTCTI.test_spi_helper_good _________________________
[gw0] linux -- Python 3.12.0 /usr/bin/python3
self = <test.test_tcti_spi_helper.TestTCTI testMethod=test_spi_helper_good>
    def test_spi_helper_good(self):
>       MySPITcti()
test/test_tcti_spi_helper.py:142: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/test_tcti_spi_helper.py:37: in __init__
    super().__init__(*args, **kwargs)
../../BUILDROOT/python-tpm2-pytss-2.1.0-1.fc39.s390x/usr/lib64/python3.12/site-packages/tpm2_pytss/TCTISPIHelper.py:210: in __init__
    raise e
../../BUILDROOT/python-tpm2-pytss-2.1.0-1.fc39.s390x/usr/lib64/python3.12/site-packages/tpm2_pytss/TCTISPIHelper.py:202: in __init__
    _chkrc(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
rc = 655369, acceptable = [0]
    def _chkrc(rc, acceptable=None):
        if acceptable is None:
            acceptable = []
        elif isinstance(acceptable, int):
            acceptable = [acceptable]
        acceptable += [lib.TPM2_RC_SUCCESS]
        if rc not in acceptable:
>           raise TSS2_Exception(rc)
E           tpm2_pytss.TSS2_Exception.TSS2_Exception: tcti:Operation timed out; function must be called again to be completed
../../BUILDROOT/python-tpm2-pytss-2.1.0-1.fc39.s390x/usr/lib64/python3.12/site-packages/tpm2_pytss/internal/utils.py:176: TSS2_Exception
----------------------------- Captured stderr call -----------------------------
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:732:Tss2_Tcti_Spi_Helper_Init() Failed waiting for TPM to become ready 
```
https://kojipkgs.fedoraproject.org//work/tasks/6251/104496251/build.log

I am not sure what could cause this issue or if it is something in our environment or in either of the tss2 packages. I am also skipping this for now on s390x.

**Comment by whooo** [comment]
> I am updating the package in Fedora and we have tree tests failing because OpenSSL in Fedora (and and RHEL based system) is for legal reasons missing some curves, namely mostly brainpool, but also the prime192v1 but also sect163r2. This makes the following tests failing:
> 
>     * `test_crypto.py`: `test_ecc_bad_curves`: Fails with message `Unsupported key format` instead of `unsupported curve: sect163r2` (I have this patched since [last version](https://src.fedoraproject.org/rpms/python-tpm2-pytss/blob/rawhide/f/python-tpm2-pytss-1.2.0-openssl.patch).
> 
>     * `test_policy.py`: `test_exec_polauth_callback` and `test_exec_sign_callback` (using the same key): Our OpenSSL fails to import the prime192v1 private key. The workaround could be to use different curve/key to make it more. So far I will skip this test downstream too, but it would be good to have an upstream and compatible solution that will work everywhere
> 

The tests are designed to check some failure modes where the cryptography module supports the curve, but the simulators are unlikely to support, so any curve that matches that criteria would work, the issue is to find a curve that works across different distributions.
Patches welcome. 

> 
> It also fails to build on 32b arch, but I do not think this is a problem for anyone in 2023.
> 
> On s390x it fails waiting for the TPM2 in this test:
> 
> I am not sure what could cause this issue or if it is something in our environment or in either of the tss2 packages. I am also skipping this for now on s390x.

Seems relevant to https://github.com/tpm2-software/tpm2-tss/issues/2531
