### ISSUE TITLE
CryptoTest::test_unsupported_key FAILED with cryptography >= 41

### ISSUE THREAD

**Issue by salahcoronya** [tpm2-software/tpm2-pytss#529]
The test suite displays "test/test_crypto.py::CryptoTest::test_unsupported_key FAILED          [ 43/569]" with the following:
```
self = <test.test_crypto.CryptoTest testMethod=test_unsupported_key>

    def test_unsupported_key(self):
        sl = dsa_private_key.strip().splitlines()
        b64 = b"".join(sl[1:-1])
        der = b64decode(b64)
    
        with self.assertRaises(ValueError) as e:
            TPMT_SENSITIVE.from_pem(der)
>       self.assertEqual(str(e.exception), "unsupported key type: _DSAPrivateKey")
E       AssertionError: 'unsupported key type: DSAPrivateKey' != 'unsupported key type: _DSAPrivateKey'
E       - unsupported key type: DSAPrivateKey
E       + unsupported key type: _DSAPrivateKey
E       ?                       +
```

It appears the key type name changed slightly in cryptography-41

See also: https://bugs.gentoo.org/911838

**Comment by whooo** [comment]
Fixed in https://github.com/tpm2-software/tpm2-pytss/commit/e4006e6066c015d9ed55befa9b98247fbdcafd7d should be in the next release

**Comment by salahcoronya** [comment]
Yes, that works. I did check the history but I must have missed that commit. The tests work once applied.
