### ISSUE TITLE
Add FAPI

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#54]
Add the feature api and test

**Comment by williamcroberts** [comment]
@joholl are you ready for FAPI to ship?

**Comment by joholl** [comment]
Sorry I did not push in quite some time. I will push tomorrow again. I've basically implemented everything but policy authorized by now :)

**Comment by williamcroberts** [comment]
> Sorry I did not push in quite some time. I will push tomorrow again. I've basically implemented everything but policy authorized by now :)

No worries, just close this ticket when you're ready so I know when I can release.

**Comment by joholl** [comment]
With #160, technically all Fapi calls are implemented. That is, if I did not forgot any.

Open issues:
* currently, we test against the default FAPI profile. If someone is using a custom one, the tests will fail. Instead, we should ship the testing profile(s) with the tests
* since we only test with the ECC profile atm, the encrypt and decrypt calls are _not tested_
* since the simulator does not ship a platform cert by default, the get_platform_certificate() call is practically _not tested_

We probably want to fix these before the release.

**Comment by williamcroberts** [comment]
> With #160, technically all Fapi calls are implemented. That is, if I did not forgot any.
> 
> Open issues:
> 
> * currently, we test against the default FAPI profile. If someone is using a custom one, the tests will fail. Instead, we should ship the testing profile(s) with the tests
> * since we only test with the ECC profile atm, the encrypt and decrypt calls are _not tested_
> * since the simulator does not ship a platform cert by default, the get_platform_certificate() call is practically _not tested_
> 
> We probably want to fix these before the release.

FYI we can mock the lib layer for things that are practically difficult to do in integration tests if that helps you get some testing around these?

**Comment by williamcroberts** [comment]
@joholl are we ready to ship the FAPI portion yet?

**Comment by joholl** [comment]
Almost. There are two things left to do:

* I'd like to add one parameter to the API, PR will follow
* We should agree on how to handle acronyms with regards to naming convention... (FapiConfig vs FAPI). This applies to classes and file names (which are kind of also part of the API). PEP-8 recommends all uppercase, I personally are indifferent. We should make it consistent, though. What do you think?

**Comment by williamcroberts** [comment]
> Almost. There are two things left to do:
> 
> * I'd like to add one parameter to the API, PR will follow

Ok

> * We should agree on how to handle acronyms with regards to naming convention... (FapiConfig vs FAPI). This applies to classes and file names (which are kind of also part of the API). PEP-8 recommends all uppercase, I personally are indifferent. We should make it consistent, though. What do you think?

I'm indifferent but I'd just align to something, pep-8 works, people know it and expect it.
