### ISSUE TITLE
Uncompleted function "verify_signature"

### ISSUE THREAD

**Issue by dj-d** [tpm2-software/tpm2-pytss#543]
Hello,
I am using version 2.1.0 of the library and I was trying to use the function `verify_signature` belonging to `FAPI` however I am not getting any return value. 
Going to check in the code I noticed that the return of the result is missing. 

Library function:
```python
def verify_signature(self, path: Union[bytes, str], digest: bytes, signature: bytes):
        path = _to_bytes_or_null(path)
        ret = lib.Fapi_VerifySignature(
            self._ctx, path, digest, len(digest), signature, len(signature)
        )
        _chkrc(ret)
```

My code
```python
try:
    result = fapi.verify_signature(
        path=<my_pub_sign_key>,
        digest=sha256(<my_digest>),
        signature=<my_signature>
    )

    print(result)
except TSS2_Exception as e:
    print(e)
```

Since we are talking about a signature scheme, I would expect the `verify_signature` function to return a boolean value to me.

Is this due to a function that has yet to be completed or because I am making spotty use of the function?

Thanks

**Comment by whooo** [comment]
Hi,

Lack of raised exception means that the signature succeeded, it might feel a bit weird but think of a signature failure as an error and therefor an exception, as such the only possible return value would always be true as any other state would lead to an exception and the function wouldn't return any value

**Comment by dj-d** [comment]
Ah ok, thanks for the explanation.

However, let's say instead of the `digest` that I used for signing, I use a `digest` that has a single different byte, in that case it would seem more correct to me to receive `False` which goes to indicate to me that the `digest` sent was not signed with that key. Receiving an exception, on the other hand, you would think more of an error of a different kind that is not necessarily related to passing a different `digest` than the signed one.

**Comment by whooo** [comment]
In that case you need to create some kind of wrapper function that checks the exception, you can compare the error property of the raised TSS2_Exception to see if the the signature verification failed or if there was any other error
