### ISSUE TITLE
ECC Encryption not yet supported

### ISSUE THREAD

**Issue by dj-d** [tpm2-software/tpm2-pytss#544]
Hello,

I am trying to use the encryption function

```python
try:
    result = fapi.encrypt(
        path=<key_path>,
        plaintext=<my_plaintext>
    )
except TSS2_Exception as e:
    print(e)
```

But I get the following error: 
```
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:332:Fapi_Encrypt_Finish() ErrorCode (0x00060002) ECC Encryption not yet supported
fapi:If called functionality isn't implemented
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:126:Fapi_Encrypt() ErrorCode(0x00060002) Data_Encrypt
```

Is this a problem with the ```tpm2-pytss``` library or the ```tpm2-tss``` library?

Thanks

**Comment by whooo** [comment]
It doesn't seem to be implemented in tpm2-tss yet, see https://github.com/tpm2-software/tpm2-tss/issues/1790

**Comment by dj-d** [comment]
Fixed in: https://github.com/tpm2-software/tpm2-tss/issues/2698
