### ISSUE TITLE
Create an ecdsa key?

### ISSUE THREAD

**Issue by torntrousers** [tpm2-software/tpm2-pytss#551]
Hello I'm trying to use tpm2-pytss and anything more than a trivial test fails, can anyone here help?

I've a LetsTrust-TPM module connected it up to a Raspberry Pi 4, configured things as deescribed [here](https://github.com/PaulKissinger/LetsTrust), and have been able to connect to it and get some random data with Python:

cat tpm-random.py
from tpm2_pytss import *
tpm = ESAPI(tcti=None)
tpm.startup(TPM2_SU.CLEAR)
r = tpm.get_random( 16 )
extradata_to_use = TPM2B_DATA(str(r))
print("TPM Randomly generated 16 data: ",str(r))

(.venv) ant@pi4-4gb:~/LetsTrust $ sudo .venv/bin/python3 tpm-random.py
TPM Randomly generated 16 data:  e171c06d8892e27329f56725313cbef8

Yay.

But I'm totally stuck getting anything more to work such as creating a key. All the examples on the Internet i try or suggested by ChatGPT or Bard fail with syntax errors or missing imports type problems , like the APIs have changed.

Would you have any simple Python code examples to show listing keys, or creating an ECDSA key, signing some data?

The end goal is using it to have the private key of a mutual TLS handshake, but any help for steps along the way would be great - create an ECDSA  key, extract its public key, sign some data, etc.

Many many thanks,

**Comment by JuergenReppSIT** [comment]
Here a primary key is used do create a signature (copied with small changes from the integration tests):
```
from tpm2_pytss import *

ectx=ESAPI()

inSensitive = TPM2B_SENSITIVE_CREATE()
inPublic = TPM2B_PUBLIC()
outsideInfo = TPM2B_DATA()
creationPCR = TPML_PCR_SELECTION()

inPublic.publicArea.type = TPM2_ALG.ECC
inPublic.publicArea.nameAlg = TPM2_ALG.SHA256
inPublic.publicArea.objectAttributes = (
            TPMA_OBJECT.USERWITHAUTH
            | TPMA_OBJECT.SIGN_ENCRYPT
            | TPMA_OBJECT.FIXEDTPM
            | TPMA_OBJECT.FIXEDPARENT
            | TPMA_OBJECT.SENSITIVEDATAORIGIN
)

inPublic.publicArea.parameters.eccDetail.scheme.scheme = TPM2_ALG.ECDSA
inPublic.publicArea.parameters.eccDetail.scheme.details.ecdsa.hashAlg = (
            TPM2_ALG.SHA256
)
inPublic.publicArea.parameters.eccDetail.symmetric.algorithm = TPM2_ALG.NULL
inPublic.publicArea.parameters.eccDetail.kdf.scheme = TPM2_ALG.NULL
inPublic.publicArea.parameters.eccDetail.curveID = TPM2_ECC.NIST_P256

sign_handle, public, creation_data, digest, ticket = ectx.create_primary(
            inSensitive, inPublic, ESYS_TR.OWNER, outsideInfo, creationPCR,
)

scheme = TPMT_SIG_SCHEME(scheme=TPM2_ALG.ECDSA)
scheme.details.any.hashAlg = TPM2_ALG.SHA256
validation = TPMT_TK_HASHCHECK(tag=TPM2_ST.HASHCHECK, hierarchy=TPM2_RH.OWNER)

digest = b"0123456789abcdef0987654321fedcba"
signature = ectx.sign(sign_handle, digest, scheme, validation)
```

**Comment by torntrousers** [comment]
Wow that ran with no errors. Thank you so much @JuergenReppSIT !

**Comment by torntrousers** [comment]
I don't really understand it though. As much as i should spend more time trying to can you explain it a bit? 
- Is the key persisted in the TOM with a lable or name or slot number or something?
- how could i print the public key, in PEM or DER or just raw X and Y?

**Comment by JuergenReppSIT** [comment]
>     * Is the key persisted in the TPM with a lable or name or slot number or something?
> 
The key is not persistent in the TPM but the same key will be produced by the next create primary. You could use evict_control to produce a persistent key (see https://tpm2-pytss.readthedocs.io/en/latest/esys.html).
>     * how could i print the public key, in PEM or DER or just raw X and Y?
you can use `public.to_pem()` in this example.

**Comment by torntrousers** [comment]
Great, and ChatGPT showed how to print the signature. So:
```
from tpm2_pytss import *

ectx=ESAPI()

inSensitive = TPM2B_SENSITIVE_CREATE()
inPublic = TPM2B_PUBLIC()
outsideInfo = TPM2B_DATA()
creationPCR = TPML_PCR_SELECTION()

inPublic.publicArea.type = TPM2_ALG.ECC
inPublic.publicArea.nameAlg = TPM2_ALG.SHA256
inPublic.publicArea.objectAttributes = (
            TPMA_OBJECT.USERWITHAUTH
            | TPMA_OBJECT.SIGN_ENCRYPT
            | TPMA_OBJECT.FIXEDTPM
            | TPMA_OBJECT.FIXEDPARENT
            | TPMA_OBJECT.SENSITIVEDATAORIGIN
)

inPublic.publicArea.parameters.eccDetail.scheme.scheme = TPM2_ALG.ECDSA
inPublic.publicArea.parameters.eccDetail.scheme.details.ecdsa.hashAlg = (
            TPM2_ALG.SHA256
)
inPublic.publicArea.parameters.eccDetail.symmetric.algorithm = TPM2_ALG.NULL
inPublic.publicArea.parameters.eccDetail.kdf.scheme = TPM2_ALG.NULL
inPublic.publicArea.parameters.eccDetail.curveID = TPM2_ECC.NIST_P256

sign_handle, public, creation_data, digest, ticket = ectx.create_primary(
            inSensitive, inPublic, ESYS_TR.OWNER, outsideInfo, creationPCR,
)

print("public key:")
print(public.to_pem().decode("utf-8"))

scheme = TPMT_SIG_SCHEME(scheme=TPM2_ALG.ECDSA)
scheme.details.any.hashAlg = TPM2_ALG.SHA256
validation = TPMT_TK_HASHCHECK(tag=TPM2_ST.HASHCHECK, hierarchy=TPM2_RH.OWNER)

digest = b"0123456789abcdef0987654321fedcba"

print("Data to sign:")
print(digest.decode("utf-8"))

signature = ectx.sign(sign_handle, digest, scheme, validation)

print()

signature_R_bytes = signature.signature.ecdsa.signatureR
signature_hex = ''.join(format(byte, '02x') for byte in signature_R_bytes)
print("Signature R in Hex:", signature_hex)

signature_S_bytes = signature.signature.ecdsa.signatureS
signature_hex = ''.join(format(byte, '02x') for byte in signature_S_bytes)
print("Signature S in Hex:", signature_hex)
```
Gives:
```
public key:
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/AnSx1vz50sGXt5ePHjslNKkrRma
b9W9gEwcw9IXjQjHSjbTM+fnZvb2V9LNnUJIbBLt2iTBUOTDMOKWNu6wYw==
-----END PUBLIC KEY-----

Data to sign:
0123456789abcdef0987654321fedcba

Signature R in Hex: ed8de938fe75044c44310d52cd588f48324272f096db4b1e3547f3ee0f734da4
Signature S in Hex: 0331bf5e8b17a86b610c32b45bf99acf994b0b11e9576d9885ebd8e0bc6f69c8
```
I've not tried to validate that signature but hopefully its good.

Could you help a little more on ```evict_control``` - 

```evict_control(auth, object_handle, persistent_handle, session1=ESYS_TR.PASSWORD, session2=ESYS_TR.NONE, session3=ESYS_TR.NONE)```

how would i fit that into the above code?

**Comment by JuergenReppSIT** [comment]
```
ectx.evict_control(ESYS_TR.OWNER, sign_handle, 0x81000001, session1=ESYS_TR.PASSWORD, session2=ESYS_TR.NONE, session3=ESYS_TR.NONE)
persistent_handle = ectx.tr_from_tpmpublic(0x81000001)
digest = b"0123456789abcdef0987654321fedcba"
signature = ectx.sign(persistent_handle, digest, scheme, validation)

```
should work. But only once because the key with the TPM handle 0x81000001 already exists ;-)
You can find good examples how do use tpm2-pytss in:
https://github.com/tpm2-software/tpm2-pytss/blob/master/test/test_esapi.py

**Comment by torntrousers** [comment]
Thanks yes that works and then only once. Is there an API I could use to check if the key/handle already exists and so only try to create/persist the key the first time and subsequent times just use the existing one?

**Comment by torntrousers** [comment]
ChatGPT suggests:
```
def check_handle_existence(handle):
    try:
        # Attempt to load the context for the specified handle
        context = ectx.context_load(handle)

        # If successful, the handle corresponds to an existing object (key)
        print(f"Handle {handle} exists.")

        # You can further use the 'context' to perform operations on the loaded object if needed

    except TpmError as e:
        # If the handle doesn't correspond to an existing object, an exception is raised
        if e.rc == TPM2_RC_HANDLE:
            print(f"No object exists for handle {handle}.")
        else:
            # Handle other exceptions if needed
            print(f"Error: {e}")

# Replace 'your_handle' with the handle you want to check
your_handle = 0x81000001  # Replace with the actual handle

# Call the function to check handle existence
check_handle_existence(your_handle)
```
bit that gives errors about:
TypeError: expected context to be TPMS_CONTEXT, got int
and
NameError: name 'TpmError' is not defined

**Comment by JuergenReppSIT** [comment]
ChatGPT suggests nonsense . E.g: context_load  needs a context and not a handle as parameter....
You can use the following code to check the existance:
```
_, prop = ectx.get_capability(TPM2_CAP.HANDLES, 0x81000001, 0x81000001)
if len(prop.data.tpmProperties.tpmProperty) == 0:
            ectx.evict_control(ESYS_TR.OWNER, sign_handle, 0x81000001, session1=ESYS_TR.PASSWORD, session2=ESYS_TR.NONE, session3=ESYS_TR.NONE)

```

**Comment by torntrousers** [comment]
Thats great, it works! Thank you again.

One final thing, I want to get the public key in PEM format for an existing key? 

For (1) Bard told me:

_In your code snippet, you are trying to create a transient object from a public key that is stored in a persistent handle. This is not possible because persistent handles are not intended to be used in this way. Persistent handles are meant to refer to objects that are stored in the TPM's persistent memory, and they cannot be used to create transient objects.

If you want to use the ectx.tr_from_tpmpublic() method, you need to first load the public key into a transient object using the ectx.context_load() method. Once the public key is in a transient object, you can then create a new transient object from it using the ectx.tr_from_tpmpublic() method._

It did provide a code example but that was full of compile errors, so how can i get the public key in PEM format for an existing TPM key handle?

**Comment by JuergenReppSIT** [comment]
> One final thing, I want to get the public key in PEM format for an existing key?

if you mean that is a persistent key you can do it as follows:
```
persistent_handle = ectx.tr_from_tpmpublic(0x81000001)
pub, _, _  = ectx.read_public(persistent_handle)
pem = pub.to_pem()
pem_string = pem.decode()
```

**Comment by torntrousers** [comment]
amazing! ChatGPT and Bard were suggesting all sorts of complicated stuff and you do it in just a few lines.

**Comment by torntrousers** [comment]
one really final thing,

how can i regenerate a key for an existing handle? So if I've already got a persistent key 0x81000001 but want that to have a new key pair?

**Comment by JuergenReppSIT** [comment]
> how can i re-generate a key for an existing handle? So if I've already got a persistent key 0x81000001 but want that to have a new key pair value?

create primary will always create the same key. If you really want do produce a new key you can create this key with the `create` function.  A  parent key (e.g. a primary key) is needed, which will be used to encrypt and decrypt the private key. 
You can load this key with the `load`function. The private and public blob should be saved to be able to load this key after the application which created the key is closed or the key can also be stored permanently with evict_control. In test_esapi.py there are several examples how to do this.

**Comment by torntrousers** [comment]
I see, thats interesting. Are there any restrictions on what i can or can't use either a primary or the other (secondary?) keys for ? Eg, i'm initially interested in using TPM keys in TLS handshakes - should either key type work for that?

**Comment by torntrousers** [comment]
For this usecase I need a key pair which provides the device identity. The private key wont leave the TPM module but a hash of the public key would provide the device identity. So it sounds like that one could be a primary key? Other keys are for things like end to end encryption and used for client keys for mutual TLS  so i suppose they might make sense being secondary keys?

**Comment by JuergenReppSIT** [comment]
@torntrousers yes that makes sense. Can we close the issue?

**Comment by torntrousers** [comment]
Yes! Thank you so much for all the help, its been amazing. Its really hard to work out how to get going from the TPM doc I can find so this has been really useful.

**Comment by JuergenReppSIT** [comment]
> Its really hard to work out how to get going with the TPM doc I can find so this has been really useful.

Also:
https://tpm2-software.github.io/tutorials/ and
https://github.com/tpm2dev/tpm.dev.tutorials
might be interesting for you.
