### ISSUE TITLE
ERROR: Could not build wheels for tpm2-pytss, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by gionny3** [tpm2-software/tpm2-pytss#553]
gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -
Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-
strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -fexceptions -g -grecord-
gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-
D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -
fcf-protection -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-
D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-
tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/include -I/usr/include/tss2 -I/usr/include/json-c -I/usr/include/uuid -
I/usr/include/tss -I/usr/include/python3.11 -c build/temp.linux-x86_64-cpython-311/tpm2_pytss._libtpm2_pytss.c -o 
build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311/tpm2_pytss._libtpm2_pytss.o
build/temp.linux-x86_64-cpython-311/tpm2_pytss._libtpm2_pytss.c:50:14: fatal error: pyconfig.h: No such file or directory
         50 | #    include <pyconfig.h>
            |              ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tpm2-pytss
Failed to build tpm2-pytss
ERROR: Could not build wheels for tpm2-pytss, which is required to install pyproject.toml-based projects

i have already installed the Dependencies following the installing steps for fedora
can anyone help me?

**Comment by whooo** [comment]
have you installed the python3-devel package? Does the file /usr/include/python3.11/pyconfig.h exist?

**Comment by gionny3** [comment]
> have you installed the python3-devel package? Does the file /usr/include/python3.11/pyconfig.h exist?

no i didn't thank u sooo much, finally i can move on hahahhah

**Comment by whooo** [comment]
good to hear that it works for you now
