### ISSUE TITLE
2.2.0 not in PyPi

### ISSUE THREAD

**Issue by Jakuje** [tpm2-software/tpm2-pytss#563]
The latest version here on github shows 2.2.0, tagged last month, while the latest version imported to pyPi is 2.1.0 (and some rc's).

Is it expected or was the import to PyPi forgotten?

**Comment by whooo** [comment]
The CI jobs failed due to changes in upstream dependencies, so it was never pushed sadly.
Waiting for someone to approve https://github.com/tpm2-software/tpm2-pytss/pull/559 so it will be pushed to pypi.

**Comment by whooo** [comment]
2,2,1 is available at pypi now

**Comment by Jakuje** [comment]
Thank you! Resolved now.
