### ISSUE TITLE
releases > 2.1.0 are not done using signed tags

### ISSUE THREAD

**Issue by dvzrv** [tpm2-software/tpm2-pytss#566]
Hi! :wave: 

I'm monitoring this project for updates on Arch Linux.

in https://github.com/tpm2-software/tpm2-pytss/blob/master/docs/release.rst#signed-tags it says, that releases above 1.0.0 are done using signed tags.

Unfortunately all releases past 2.1.0 are done without a signed tag and downstream we can not validate the trust path between these releases.

@whooo: Can you create another release using a signed tag?
@williamcroberts can you add @whooo's OpenPGP fingerprint to the release.rst document in a signed commit so that we can verify it? Alternatively/ Additionally it is possible for us to use thirdparty certifications (aka. "a signature on a key"), so if you could sign @whooo's key and publish this certification on relevant keyservers, that'd be great!

As is, the status quo unfortunately blocks us from upgrading.

**Comment by whooo** [comment]
I'll sign the next tag with 0x28630DB7CEE35E6F

**Comment by Foxboron** [comment]
@whooo Still need a trust path between you and the previous maintainer.

**Comment by williamcroberts** [comment]
@Foxboron I don't have access to any previous keys used to cut any releases. But I'd be more than happy to add a fingerprint and sign the commit with my current keys.

The requirement to provide "perfect PKI isms" between maintainers was never a goal. We can try to get better, but many of us switched jobs and didn't/forgot to tote are keys along or sign new ones before we exited.

**Comment by Foxboron** [comment]
> The requirement to provide "perfect PKI isms" between maintainers was never a goal. We can try to get better, but many of us switched jobs and didn't/forgot to tote are keys along or sign new ones before we exited.

But then you should have figured detailed the release section a bit more then leaving it up for interpretations what "a maintainer" actually entails.

My suggestion is for you to upload your current keys to github, then sign a statement that contains the keys of the current maintainers.

Then keep a list of current maintainers *somewhere* in the repo so it's clear.

**Comment by williamcroberts** [comment]
> > The requirement to provide "perfect PKI isms" between maintainers was never a goal. We can try to get better, but many of us switched jobs and didn't/forgot to tote are keys along or sign new ones before we exited.
> 
> But then you should have figured detailed the release section a bit more then leaving it up for interpretations what "a maintainer" actually entails.

What's confusing about this?
- https://github.com/tpm2-software/tpm2-pytss/blob/master/docs/release.rst

Patches to enhance clarity are always welcome.

> My suggestion is for you to upload your current keys to github, then sign a statement that contains the keys of the current maintainers.
> 

Per https://github.com/tpm2-software/tpm2-pytss/blob/master/docs/release.rst, maintainers keys should be discoverable on a public key server and be associated with your github account. I am not sure if I made my most recent key discoverable on the public key servers yet.

My current keys are here:
  - https://github.com/williamcroberts.gpg

> Then keep a list of current maintainers _somewhere_ in the repo so it's clear.

Like this?
  - https://github.com/tpm2-software/tpm2-pytss/blob/master/docs/maintainers.rst

We we're never following our release doc AFAICT. This was probably copy+pasted from our other projects and I don't think we signed the release tarballs because they are hosted on pypi which is where most folks go and gpg support was removed. You can pip install straight from git url as well which has all the integrity verification of git.

I doubt we will ever get perfect key provenience, it's an admirable goal, I will post a signed commit of @whooo 's key

**Comment by Foxboron** [comment]
> We we're never following our release doc AFAICT. This was probably copy+pasted from our other projects and I don't think we signed the release tarballs because they are hosted on pypi which is where most folks go and gpg support was removed. You can pip install straight from git url as well which has all the integrity verification of git.

To be clear, we are packing this for Arch Linux. We are not going to pip install this straight from the git remote when we have been using signed releases previously.

**Comment by williamcroberts** [comment]
> A 3 year old document done with an unsigned commit, where I have to guess that one of the people on that list is this account isn't a good document.

Your trusting the code already. Lots of stuff is older than 3 years. First you say we don't have anything documented, then your wrong and then say it's too old. If theirs anything you want changed, patches are welcome.

> To be clear, we are packing this for Arch Linux. We are not going to pip install this straight from the git remote when we have been using signed releases previously.

Am I crazy? None of our releases were signed for tpm2-pytss.

Your distro users trust you

**Comment by Foxboron** [comment]
> Your trusting the code already. Lots of stuff is older than 3 years. First you say we don't have anything documented, then your wrong and then say it's too old. If theirs anything you want changed, patches are welcome.

I'm trusting the release signed by you. Not any arbitrary code that is being commit to this repository.


> First you say we don't have anything documented, then your wrong and then say it's too old.

I wrote that the release section should be clearer. Not that nothing was documented.

> Am I crazy? None of our releases were signed for tpm2-pytss.
> Your distro users trust you

Yes, they trust us. And it's our job to figure out if we trust upstream releases of security critical software.

All previous releases from 1.0.0 and up until 2.1.0. 
I don't remember why it sometimes doesn't *show* in Github but there is a difference between signing the commit, tag and tag ref.

```
λ tpm2-pytss master Ɇ » git tag --verify 2.1.0
object 9f27d0c0bdd42574b158c0372213e259fad80798
type commit
tag 2.1.0
tagger William Roberts <william.c.roberts@intel.com> 1673278417 -0600

2.1.0 - 2022-01-09

Fixed
- using tpm2-pytss in unit tests within a mocked environment see #481.

Added
- tpm2-tools like strings via parse for TPM2_SYM_DEF and TPM2_SYM_DEF_OBJECT structures.
- support for algorithms strings in ESAPI start_auth_session.
- utils: credential_to_tools and tools_to_credential to convert to and from tpm2-tools makecredential outputs.
- TCTI: Add bindings to TCTISpiHelper.
gpg: WARNING: unsafe permissions on homedir '/home/fox/.config/gnupg'
gpg: Signature made Mon 09 Jan 2023 04:33:45 PM CET
gpg:                using RSA key 5B482B8E3E19DA7C978E1D016DE2E9078E1F50C1
gpg: Can't check signature: No public key
λ tpm2-pytss master Ɇ » git tag --verify 2.2.0
error: 2.2.0: cannot verify a non-tag object of type commit.
λ tpm2-pytss master Ɇ » git tag --verify 2.2.1
error: 2.2.1: cannot verify a non-tag object of type commit.
````

**Comment by williamcroberts** [comment]
Ahh, there's the miscommunication, release for me is the sdist tarball not the tag. Yes, a couple of the tags were not signed, but future tags will be, it was just a missed step in the documented release process.

I looked to see if there was a way to only allow signed tags to be pushed, but I didn't find the right features to twiddle on GitHub for that, if anyone knows how to enable something like that, that'd be a nice feature to have.

**Comment by Foxboron** [comment]
> Ahh, there's the miscommunication, release for me is the sdist tarball not the tag. Yes, a couple of the tags were not signed, but future tags will be, it was just a missed step in the documented release process.

The initial issue only mentioned "signed tags" from the get go so I'm not sure how we could have been more clear. Generally I would prefer a signed tarball, but an `sdist` usually miss the test suite which makes it less usefull. Even when signed.

As a result we usually check for signed tags from the git remote directly as we can run any tests and authenticate the sources.


> I looked to see if there was a way to only allow signed tags to be pushed, but I didn't find the right features to twiddle on GitHub for that, if anyone knows how to enable something like that, that'd be a nice feature to have.

I don't think that is possible yet.

**Comment by williamcroberts** [comment]
> > Ahh, there's the miscommunication, release for me is the sdist tarball not the tag. Yes, a couple of the tags were not signed, but future tags will be, it was just a missed step in the documented release process.
> 
> The initial issue only mentioned "signed tags" from the get go so I'm not sure how we could have been more clear. 

The verbage changed (tags vs release)  and the thread dissolved into more discussions on other key management practices.

> Generally I would prefer a signed tarball, but an `sdist` usually miss the test suite which makes it less usefull. Even when signed.
> 
> As a result we usually check for signed tags from the git remote directly as we can run any tests and authenticate the sources.

What do you do if a project doesn't do anything, their has to be a pile of those?

> 
> > I looked to see if there was a way to only allow signed tags to be pushed, but I didn't find the right features to twiddle on GitHub for that, if anyone knows how to enable something like that, that'd be a nice feature to have.
> 
> I don't think that is possible yet.

**Comment by Foxboron** [comment]
> What do you do if a project doesn't do anything, their has to be a pile of those?

We package it without signatures, we can't solve that problem.

When a signed upstream becomes unsigned we will refrain from updating until we understand why. Which results in issues like this.
