### ISSUE TITLE
nv_create return code

### ISSUE THREAD

**Issue by terilenard** [tpm2-software/tpm2-pytss#574]
Currently, nv_create in fapi does not return a value, only verifies the return code. It is possible to have the function extended to return the code, similarly as create_key in fapi?

**Comment by whooo** [comment]
Just so I understand, you want it to return True or False depending on if the path already exists if exists_ok=True is passed to the function?

**Comment by terilenard** [comment]
> Just so I understand, you want it to return True or False depending on if the path already exists if exists_ok=True is passed to the function?

That can work, similar as it is done in other functions :)

**Comment by whooo** [comment]
Added in https://github.com/tpm2-software/tpm2-pytss/pull/578
If possible, please test the PR so I'm sure it solves your issues
