### ISSUE TITLE
Buffer protocol for simple TPM2B types

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-pytss#71]
The TPM2B structs that are just size + fixed size byte array, such as TPM2B_DIGEST and TPM2B_PUBLIC_KEY_RSA should behave as the python bytes type.
A simple example is doing PCR_Read and then printing the value of each digest in TPML_DIGEST using base64.b16encode without having to convert each entry.

**Comment by williamcroberts** [comment]
Do you have sample code for how it is now and how you want it?

**Comment by whooo** [comment]
Working example:

```
from tpm2_pytss import *                                                                                                                                                                                                               
from base64 import b16encode                                                                                                                                                                                                           
                                                                                                                                                                                                                                       
ectx = ESAPI()                                                                                                                                                                                                                         
                                                                                                                                                                                                                                       
selection = TPMS_PCR_SELECTION()                                                                                                                                                                                                       
selection.hash = TPM2_ALG.SHA256                                                                                                                                                                                                       
selection.sizeofSelect=3                                                                                                                                                                                                               
selection.pcrSelect=b'\x00\x00\xFF'                                                                                                                                                                                                    
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                       
sels = TPML_PCR_SELECTION()                                                                                                                                                                                                            
sels.count=1                                                                                                                                                                                                                           
sels.pcrSelections = (selection[0],)                                                                                                                                                                                                   
                                                                                                                                                                                                                                       
uc, selout, digests = ectx.PCR_Read(sels)                                                                                                                                                                                              
                                                                                                                                                                                                                                       
for i in range(0, digests.count):                                                                                                                                                                                                      
    d = ffi.buffer(digests.digests[i].buffer)                                                                                                                                                                                          
    print(b16encode(d))
```

How I think it should work (excluding setting the pcrSelect)
```
from tpm2_pytss import *                                                                                                                                                                                                               
from base64 import b16encode                                                                                                                                                                                                           
                                                                                                                                                                                                                                       
ectx = ESAPI()                                                                                                                                                                                                                         
                                                                                                                                                                                                                                       
pcrsel = TPMS_PCR_SELECTION(                                                                                                                                                                                                           
    hash=TPM2_ALG_SHA256,                                                                                                                                                                                                              
    pcrSelect=(0xFF,)                                                                                                                                                                                                                  
)                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                       
pcrsels = TPML_PCR_SELECTION(                                                                                                                                                                                                          
    (pcrsel,)                                                                                                                                                                                                                          
)                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                       
uc, outsel, digests = ectx.PCR_Read(pcrsels)                                                                                                                                                                                           
                                                                                                                                                                                                                                       
for d in digests:                                                                                                                                                                                                                      
    h = b16encode(d)                                                                                                                                                                                                                   
    print(h)
```

**Comment by williamcroberts** [comment]
@whooo I have something started as PR #73.

But I wonder if I should add onto this where we return a dict() mapping PCR index to byte array.

**Comment by williamcroberts** [comment]
The other question is, once we unpack this structure, do folks need the binary representation for anything else? Perhaps it would be better if we had callers call TPML_unpack rather than internally to esys.

@AndreasFuchsSIT any thoughts? @pdxjohnny inputs?

**Comment by whooo** [comment]
I had some thoughts about this (and the general issue of making the different types more pythonic) but haven't had time to put something together yet.
The general idea is to make all the types in types.py real objects and move the conversion between the python objects and thecffi representation to the API calls and the python object parent.
The problem I see with just using unpack functions is that children (such as the public key in a TPM2B_PUBLIC) still need to be handles by the user of the API

I included some probably not working code as an example

`diff --git a/tpm2_pytss/ESAPI.py b/tpm2_pytss/ESAPI.py
index 85fa132..d5d6db4 100644
--- a/tpm2_pytss/ESAPI.py
+++ b/tpm2_pytss/ESAPI.py
@@ -1211,7 +1211,7 @@ class ESAPI:
                 pcrValues,
             )
         )
-        return (pcrUpdateCounter[0], pcrSelectionOut[0], pcrValues[0])
+        return (pcrUpdateCounter[0], pcrSelectionOut[0], TPML_DIGEST(cdata=pcrValues[0]))
 
     def PCR_Allocate(
         self,
@@ -1398,7 +1398,7 @@ class ESAPI:
 
         _chkrc(
             lib.Esys_PolicyOR(
-                self.ctx, policySession, session1, session2, session3, pHashList
+                self.ctx, policySession, session1, session2, session3, pHashList._cdata
             )
         )
 
diff --git a/tpm2_pytss/types.py b/tpm2_pytss/types.py
index 69a0594..4dec6e4 100644
--- a/tpm2_pytss/types.py
+++ b/tpm2_pytss/types.py
@@ -891,9 +891,19 @@ class TPML_CCA(object):
 
 
 class TPML_DIGEST(object):
-    def __new__(self):
-        return ffi.new("TPML_DIGEST *")
-
+    def __init__(self, cdata=None):
+        if cdata is None:
+            self._cdata = cdata
+        else:
+            self._cdata = ffi.new("TPML_DIGEST *")
+
+    def __len__(self):
+        return self._cdata.count
+
+    def __getitem__(self, key):
+        if key >= self._cdata.count:
+            raise Exception("out of range etc")
+        return TPM2B_DIGEST(cdata=self._cdata.digests[key])
 
 class TPML_DIGEST_VALUES(object):
     def __new__(self):
`

This would provide other possibilities as well, such as attaching (un)marshal methods directly to the instance, writing iterators and passing values and initialization time (TPM2B_DIGEST(buffer=bunch_of_bytes)).

**Comment by williamcroberts** [comment]
> I had some thoughts about this (and the general issue of making the different types more pythonic) but haven't had time to put something together yet.
> The general idea is to make all the types in types.py real objects and move the conversion between the python objects and thecffi representation to the API calls and the python object parent.
> The problem I see with just using unpack functions is that children (such as the public key in a TPM2B_PUBLIC) still need to be handles by the user of the API
> 
> I included some probably not working code as an example
> 
> ```
> diff --git a/tpm2_pytss/ESAPI.py b/tpm2_pytss/ESAPI.py
> index 85fa132..d5d6db4 100644
> --- a/tpm2_pytss/ESAPI.py
> +++ b/tpm2_pytss/ESAPI.py
> @@ -1211,7 +1211,7 @@ class ESAPI:
>                  pcrValues,
>              )
>          )
> -        return (pcrUpdateCounter[0], pcrSelectionOut[0], pcrValues[0])
> +        return (pcrUpdateCounter[0], pcrSelectionOut[0], TPML_DIGEST(cdata=pcrValues[0]))
>  
>      def PCR_Allocate(
>          self,
> @@ -1398,7 +1398,7 @@ class ESAPI:
>  
>          _chkrc(
>              lib.Esys_PolicyOR(
> -                self.ctx, policySession, session1, session2, session3, pHashList
> +                self.ctx, policySession, session1, session2, session3, pHashList._cdata
>              )
>          )
>  
> diff --git a/tpm2_pytss/types.py b/tpm2_pytss/types.py
> index 69a0594..4dec6e4 100644
> --- a/tpm2_pytss/types.py
> +++ b/tpm2_pytss/types.py
> @@ -891,9 +891,19 @@ class TPML_CCA(object):
>  
>  
>  class TPML_DIGEST(object):
> -    def __new__(self):
> -        return ffi.new("TPML_DIGEST *")
> -
> +    def __init__(self, cdata=None):
> +        if cdata is None:
> +            self._cdata = cdata
> +        else:
> +            self._cdata = ffi.new("TPML_DIGEST *")
> +
> +    def __len__(self):
> +        return self._cdata.count
> +
> +    def __getitem__(self, key):
> +        if key >= self._cdata.count:
> +            raise Exception("out of range etc")
> +        return TPM2B_DIGEST(cdata=self._cdata.digests[key])
>  
>  class TPML_DIGEST_VALUES(object):
>      def __new__(self):
> ```
> 
> This would provide other possibilities as well, such as attaching (un)marshal methods directly to the instance, writing iterators and passing values and initialization time (TPM2B_DIGEST(buffer=bunch_of_bytes)).

I thought about making them actual types as well, it's just so much work, but I think it would make the interfaces cleaner. I like the concept of having the marshaling routines part of the actual python type.

It's a whole tone more work, but I think in the end it's the way to go.

**Comment by williamcroberts** [comment]
I started playing around with this concept, but my offhand thought is that if we have to manually add all the gets/sets, which gets nasty in nested structures and all the associated conversions than we should have just used ctypes; we seem to be loosing the gains of using CFFI.

**Comment by whooo** [comment]
Yeah, it will be a lot of work, but if the object is only responsible for its direct children it might be easier, so for example TPM2B_PUBLIC is only responsible for publicArera, TPMT_PUBLIC is responsible for type, nameAlg, objectAttributes, authPolicy, parameters, unique, parameters is responsible for its direct children etc.

While it is a lot of work, not doing it would simply move the work to the users of the API.

I'm willing to spend some time on doing the boring work if you decide to continue with cffi

**Comment by williamcroberts** [comment]
@whooo this was bothering me, so I started trying something over here:
  - https://github.com/williamcroberts/tpm2-pytss/commit/e6d8f0e0bc680d6d9a8c353b48f8447d8a245224

In a nutshell, I very carefully crafted a base class that I think we can inherit all types from and it should just work. It uses some trickery to override __setattr__ and __getattribute__. I didn't know about __getattribute__, so before I was trying __getattr__ and it wasn't working. This seems to handle nested structures without us having to hand jam all that code.
