### ISSUE TITLE
TPM2B_PUBLIC and TPM2B_SENSITIVE from PEM files

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#88]
create TPM2B_PUBLIC.fromPEM() and TPM2B_SENSITIVE.fromPEM routines to convert those data types for things like LoadExternal. Also support a fromAES? How do we want to handle symmetric keys? Should we just be able to pass a pem to the existing parse routines?

**Comment by williamcroberts** [comment]
@whooo what do you think about how you'd like to see this interface? Any chance you got bandwith to work on it while I continue testing other parts of ESAPI bindings?

**Comment by whooo** [comment]
I could work on this (I already have code that does), but it creates some questions, how heavy can we be on dependencies? I like python-cryptography ( https://cryptography.io/en/latest/ ), but least an ASN.1 parser module is required, also should there be any default object attributes for the public part?

I'll look into adding a toPEM method for TPM2B_PUBLIC as well.

**Comment by williamcroberts** [comment]
> I could work on this (I already have code that does), but it creates some questions, how heavy can we be on dependencies? I like python-cryptography ( https://cryptography.io/en/latest/ ), but least an ASN.1 parser module is required, also should there be any default object attributes for the public part?
> 
> I'll look into adding a toPEM method for TPM2B_PUBLIC as well.

Use whatever makes sense, I would use Python Cryptography as that seems to be the defacto standard. I wouldn't worry about dependencies, we are already in Python. Just make sure we update the setup.cfg to include them so pip install doesn't miss anything.

For object attributes, I would require the caller to specify them or manually set them in the returned TPM2B_XXX object.

For toPEM routines, we want to use the format for private objects that tpm2-openssl uses:
  - https://github.com/tpm2-software/tpm2-openssl/blob/master/src/tpm2-provider-pkey.c#L12

That structure is what needs to be duplicated, it gets written as an ASN1.

As always, thanks. I appreciate your help. I'll have to set up an Authors file and make sure you end up in it.

**Comment by whooo** [comment]
I might have to create two to methods, I see a use of just getting the public key as a standard PEM file, so you can for example verify a signature from the TPM using the openssl CLI, so perhaps toPEM for a standard rsa public key and toTSSKey for the tpm2-opemssl format?

I might add support for loading the public key from a certificate as well, using fromPEM for TPM2B_PUBLIC.

**Comment by whooo** [comment]
It seems that the tpm2-openssl format requires both the public and private part at the same time (and some other metadata(, so I might do two more format functions in crypto for that (would be nice if you could to both to and from conversion)

**Comment by williamcroberts** [comment]
> I might have to create two to methods, I see a use of just getting the public key as a standard PEM file, so you can for example verify a signature from the TPM using the openssl CLI, so perhaps toPEM for a standard rsa public key and toTSSKey for the tpm2-opemssl format?
> 
> I might add support for loading the public key from a certificate as well, using fromPEM for TPM2B_PUBLIC.

For a PUBLIC key PEM format, their is no difference. It's all the same between various PEM consumers, since all the data is public. It's only for the private/sensitive portion. Since we don't have the key data itself, it has it's own format. So the private handling routine needs that extra data at formatting time. Does that make sense? Did I understand correctly?

**Comment by whooo** [comment]
yeah, I think so, I added toPEM for TPM2B_PUBLIC, but my thought is that the tpm2-openssl format should have a class something like TSS2Key, and then attach asn1 (de)serialization methods there, together with the other needed information (parent and emptyAuth)

I might do another pull request for that, I just need to understand some things about tpm2-openssl and setup some kind of test for it as well

**Comment by williamcroberts** [comment]
> yeah, I think so, I added toPEM for TPM2B_PUBLIC, but my thought is that the tpm2-openssl format should have a class something like TSS2Key, and then attach asn1 (de)serialization methods there, together with the other needed information (parent and emptyAuth)

Sounds good

> 
> I might do another pull request for that, I just need to understand some things about tpm2-openssl and setup some kind of test for it as well

That's fine, we can definitely take these piecemeal so you don't have to maintain things out of tree.

**Comment by williamcroberts** [comment]
Ill keep this open so we know to:
  - [ ] TPMT_PUBLIC fromPEM
    - I would consider refactoring the crypto api to expect the TPMT_PUBLIC
  - [ ] TPMT_SENSITIVE toPEM using TSS format
  - [ ] TPM2B_SENSITIVE toPEM using TSS format

**Comment by whooo** [comment]
I'm a bit unsure about having the TSS format connected to TPMT_SENSITIVE, so my baisc understanding of the format is that it has four fields, public, private, emptyAuth and parent, so using TPMT_SENSITIVE only might be weird as you need to pass the other values then TPMT_SENSITIVE to toPEM in that case

**Comment by williamcroberts** [comment]
> I'm a bit unsure about having the TSS format connected to TPMT_SENSITIVE, so my baisc understanding of the format is that it has four fields, public, private, emptyAuth and parent, so using TPMT_SENSITIVE only might be weird as you need to pass the other values then TPMT_SENSITIVE to toPEM in that case

Disregard the private and public fields are from the create call. So it's only the TPM2B_PRIVATE

**Comment by whooo** [comment]
I'm not aware of any PEM-style format for TPM2B_PRIVATE on it own, are you thinking of marshaling a TPM2B_PRIVATE, base64 encode it and then wrap it in PEM header and footer?

**Comment by williamcroberts** [comment]
I think this is closed now dfbb821081
