### ISSUE TITLE
make size a read only property

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#89]
Make size a read only property. What about count? I could see folks wanted to set count on TPML objects if they go through __setattr__ and modify things in a way the count tracker doesn't get it right.

**Comment by williamcroberts** [comment]
@whooo thoughts here as well? Do you want to work on this?

**Comment by whooo** [comment]
I'm currently working on a TPM2B_OBJECT class where the idea is to make size read only (and buffer), so the answer is yes.

I mostly worry that the count attribute/field and the actual number of elements will get out of sync unless it's read only and that will lead to annoying bugs. That might require that both the count and array attributes are read only and that everything has to go thought `__setitem__` and `__getitem__' tho.

Do you have any examples where you think people might want to write to the attributes directly?

**Comment by whooo** [comment]
I created https://github.com/tpm2-software/tpm2-pytss/pull/90

**Comment by williamcroberts** [comment]
Their actually might be a case where someone makes a Data structure, and then wants to chop the count/size field for some reason.

**Comment by whooo** [comment]
With count, sure, as long as people to either do it by hand or use a list-style API but not at the same time.
For size/TPM2B I wish to them behave as close as possible to python bytes, including being immutable, so if you change them, change the whole set a one time.

**Comment by williamcroberts** [comment]
> With count, sure, as long as people to either do it by hand or use a list-style API but not at the same time.
> For size/TPM2B I wish to them behave as close as possible to python bytes, including being immutable, so if you change them, change the whole set a one time.

Seems reasonable to me, especially considering it follows bytes API. Good point.

**Comment by whooo** [comment]
As the TPM2B_SIMPLE_OBJECT is merged I think this can be closed, what do you say?
